# -*- coding: utf-8 -*-
"""Дополнительные главы: ваниль, разведка биомов, кухня, рельсы, боеприпасы, побочное Eternal Tales."""
from dsl import chapter, Q, item, give, adv, dim, biome, check, loot, chain

E = "eternal_tales:"

chapter(
    "more_vanilla", "more", 10, "Старые дороги", "minecraft:diamond",
    "Ванильная прогрессия, о которой сборка не даёт забыть",
    [
        "Под девяноста модами лежит та же игра: алмазы на глубине, стол зачарований, "
        "незерит, маяк. Моды не отменяют её — они делают её быстрее и красивее.",
    ],
    chain([
        Q("diamonds", "Алмазы", "minecraft:diamond", 0, 0,
          text=["На минус пятьдесят восьмом. Кирка, потом всё остальное."],
          tasks=[item("minecraft:diamond", 16)], rewards=loot(("minecraft:diamond", 4), xp=40)),
        Q("enchant", "Стол зачарований", "minecraft:enchanting_table", 0, 1,
          text=["Пятнадцать полок, лазурит, удача. Астральный зачарователь Eternal Tales "
                "позже сделает то, что этот стол не умеет."],
          tasks=[item("minecraft:enchanting_table"), item("minecraft:bookshelf", 15)],
          rewards=loot(("minecraft:lapis_lazuli", 32), ("minecraft:experience_bottle", 16), xp=60)),
        Q("villagers", "Торговля", "minecraft:emerald", 1, 1,
          text=["Изумруды и жители в блоках Easy Villagers. Библиотекарь с починкой — "
                "цель номер один."],
          tasks=[item("minecraft:emerald", 32), item("easy_villagers:trader")],
          rewards=loot(("minecraft:emerald", 16), xp=50)),
        Q("netherite", "Незерит", "minecraft:netherite_ingot", 0, 2,
          text=["Четыре обломка, четыре золота. Одна вещь для себя, остальное — "
                "в водолазный комплект и пушки."],
          tasks=[item("minecraft:netherite_ingot", 4)], rewards=loot(("minecraft:netherite_scrap", 4), xp=100)),
        Q("beacon", "Маяк", "minecraft:beacon", 0, 3,
          text=["Звезда иссушителя и пирамида. Скорость на всей базе — маленький "
                "модуль MekaSuit за много часов до MekaSuit."],
          tasks=[item("minecraft:beacon"), item("minecraft:iron_block", 9)],
          rewards=loot(("minecraft:iron_block", 16), xp=200)),
        Q("trims", "Отделка брони", "minecraft:smithing_table", 1, 3,
          text=["Шаблоны отделки — ванильные и из модов: Eternal Tales добавляет шестьдесят "
                "материалов и тридцать узоров."],
          tasks=[item("minecraft:smithing_table"), check("Нанести отделку на любую броню")],
          rewards=loot(("minecraft:amethyst_shard", 16), xp=40)),
        Q("elytra2", "Элитры и ракеты", "minecraft:firework_rocket", 0, 4,
          text=["Шестьдесят четыре ракеты. Пока модули полёта далеко, это небо."],
          tasks=[item("minecraft:elytra"), item("minecraft:firework_rocket", 64)],
          rewards=loot(("minecraft:firework_rocket", 64), xp=100)),
    ]),
)

chapter(
    "more_explore", "more", 20, "Атлас", "minecraft:filled_map",
    "Биомы Terralith и чужих миров",
    [
        "Мир сборки собран из двух генераторов, и большую его часть вы не увидите, "
        "если не пойдёте специально. Этот атлас — список мест, ради которых стоит "
        "идти. Книга отмечает биом, как только вы в нём стоите.",
    ],
    [
        Q("sakura", "Сакуровая роща", "minecraft:cherry_sapling", 0, 0,
          text=["Розовый лес Terralith. Ставьте здесь дом — вы всё равно захотите."],
          tasks=[biome("terralith:sakura_grove")], rewards=loot(("minecraft:cherry_sapling", 8), xp=30)),
        Q("lavender", "Лавандовая долина", "minecraft:purple_dye", 1, 0,
          text=["Лавандовые поля Terralith — долина и лес рядом. Найдите оба."],
          tasks=[biome("terralith:lavender_valley"), biome("terralith:lavender_forest")],
          rewards=loot(("minecraft:purple_dye", 32), xp=40)),
        Q("amethyst", "Аметистовый каньон", "minecraft:amethyst_shard", 2, 0,
          text=["Фиолетовый камень и кристаллы, растущие из стен."],
          tasks=[biome("terralith:amethyst_canyon")], rewards=loot(("minecraft:amethyst_shard", 32), xp=40)),
        Q("glacial", "Ледниковая расселина", "minecraft:packed_ice", 3, 0,
          text=["Самое холодное и самое глубокое место Terralith."],
          tasks=[biome("terralith:glacial_chasm")], rewards=loot(("minecraft:blue_ice", 16), xp=50)),
        Q("skylands", "Небесные земли", "minecraft:feather", 0, 1,
          text=["Острова в воздухе, ещё до Aether. Весенние, осенние — любые."],
          tasks=[biome("terralith:skylands_spring")], rewards=loot(("minecraft:feather", 32), xp=60)),
        Q("volcano", "Кальдера", "minecraft:magma_block", 1, 1,
          text=["Вулкан Terralith с озером внутри."],
          tasks=[biome("terralith:caldera")], rewards=loot(("minecraft:magma_block", 32), xp=50)),
        Q("mystic", "Изумрудные пики", "minecraft:emerald", 2, 1,
          text=["Зелёные горы Terralith, где изумруд лежит не только в жилах."],
          tasks=[biome("terralith:emerald_peaks")], rewards=loot(("minecraft:emerald", 8), xp=50)),
        Q("ominous", "Вулканический кратер", "minecraft:magma_block", 3, 1,
          text=["Ещё один вулкан Terralith — с озером лавы вместо воды."],
          tasks=[biome("terralith:volcanic_crater")], rewards=loot(("minecraft:magma_block", 32), xp=50)),
        Q("redwood", "Облачный лес", "minecraft:moss_block", 0, 2,
          text=["Туман между стволами и мох по колено."],
          tasks=[biome("terralith:cloud_forest")], rewards=loot(("minecraft:moss_block", 32), xp=40)),
        Q("wasteland", "Расписные горы", "minecraft:orange_terracotta", 1, 2,
          text=["Полосатые склоны из терракоты всех оттенков."],
          tasks=[biome("terralith:painted_mountains")], rewards=loot(("minecraft:orange_terracotta", 32), xp=40)),
        Q("hotsprings", "Лунная роща", "minecraft:glow_lichen", 2, 2,
          text=["Ночной биом, светящийся собственным светом."],
          tasks=[biome("terralith:moonlight_grove")], rewards=loot(("minecraft:glow_lichen", 16), xp=40)),
        Q("endbop", "Мираж", "minecraft:sand", 3, 2,
          text=["Острова-миражи посреди тёплого океана."],
          tasks=[biome("terralith:mirage_isles")], rewards=loot(("minecraft:sand", 64), xp=80)),
        Q("geob", "Геобстрактсайт", E + "geobstractsite", 0, 3,
          text=["Радиоактивный биом Eternal Tales в обычном мире. Не задерживайтесь."],
          tasks=[biome(E + "geobstractsite_biome")], rewards=loot((E + "uranium", 8), xp=80)),
        Q("mucun", "Мукунфекцио", E + "mucunfectio_sand", 1, 3,
          text=["Карантинная зона. Крабы."],
          tasks=[biome(E + "mucunfectio_abyss")], rewards=loot((E + "crabsburger", 4), xp=80)),
        Q("amberian", "Янтарный город", E + "amber_bricks", 2, 3,
          text=["Столица Королевства Янтаря."],
          tasks=[biome(E + "amberian_city")], rewards=loot((E + "amber_bricks", 64), xp=150)),
        Q("atlas_done", "Атлас заполнен", "minecraft:filled_map", 3, 3,
          deps=["sakura", "lavender", "amethyst", "glacial", "skylands", "volcano", "mystic", "ominous",
                "redwood", "wasteland", "hotsprings", "endbop", "geob", "mucun", "amberian"],
          text=["Пятнадцать мест, в которых вы стояли. Карта Xaero помнит каждое."],
          tasks=[item("minecraft:filled_map")],
          rewards=loot(("waystones:waystone", 4), ("waystones:warp_dust", 32), xp=400)),
    ],
)

chapter(
    "more_kitchen", "more", 30, "Поварская книга", "farmersdelight:skillet",
    "Farmer's Delight, кухня MineColonies и еда Eternal Tales",
    [],
    chain([
        Q("stew", "Три супа", "farmersdelight:beef_stew", 0, 0,
          text=["Говяжье рагу, куриный суп, рыбная похлёбка. Котелок и терпение."],
          tasks=[give("farmersdelight:beef_stew", 4), give("farmersdelight:chicken_soup", 4), give("farmersdelight:fish_stew", 4)],
          rewards=loot(("farmersdelight:rich_soil", 16), xp=60)),
        Q("bread", "Сэндвичи", "farmersdelight:bacon_sandwich", 0, 1,
          text=["Бекон, курица, яйцо — между двумя ломтями. Еда в дорогу."],
          tasks=[give("farmersdelight:bacon_sandwich", 8), give("farmersdelight:chicken_sandwich", 8)],
          rewards=loot(("minecraft:bread", 32), xp=50)),
        Q("pies", "Пироги", "farmersdelight:apple_pie", 0, 2,
          text=["Яблочный, шоколадный, сладкие ягоды. Целиком — на стол."],
          tasks=[give("farmersdelight:apple_pie", 2), give("farmersdelight:chocolate_pie", 2)],
          rewards=loot(("minecraft:cocoa_beans", 32), ("minecraft:sugar", 32), xp=60)),
        Q("colony_food", "Кухня колонии", "minecolonies:cheese_pizza", 0, 3,
          text=["MineColonies добавляет десятки блюд: пицца, борщ, кимчи, лембас. "
                "Повар делает их сам, но и вы можете."],
          tasks=[give("minecolonies:cheese_pizza", 2), give("minecolonies:borscht", 4)],
          rewards=loot(("minecolonies:lembas_scone", 8), xp=80)),
        Q("et_food", "Еда чужих миров", E + "crabsburger", 0, 4,
          text=["Крабсбургер, мутатонговая похлёбка, печенье с голубикой. Eternal Tales "
                "кормит странно, но сытно."],
          tasks=[adv(E + "get_crabsburger"), adv(E + "eat_mutatongue_chowder"), adv(E + "yummy")],
          rewards=loot((E + "energy_drink", 4), xp=120)),
        Q("feast_hall", "Пир", "farmersdelight:honey_glazed_ham", 0, 5,
          text=["Окорок в мёде, жареная курица, запечённая треска — три пиршества "
                "на одном столе. Зовите ребят."],
          tasks=[give("farmersdelight:honey_glazed_ham", 2), give("farmersdelight:roast_chicken_block", 2),
                 give("farmersdelight:stuffed_pumpkin_block", 1)],
          rewards=loot(("farmersdelight:netherite_knife", 1), xp=200)),
    ]),
)

chapter(
    "more_rails", "more", 40, "Депо", "railways:conductor_cap",
    "Steam 'n' Rails во всей красе",
    [],
    chain([
        Q("locomotive", "Паровоз", "railways:smokestack_coalburner", 0, 0,
          text=["Труба, котёл, дымовая коробка, обшивка. Локомотив, который выглядит "
                "как локомотив."],
          tasks=[item("railways:smokestack_coalburner"), item("railways:locometal_boiler", 4), item("railways:locometal_smokebox")],
          rewards=loot(("railways:brass_wrapped_locometal", 32), xp=80)),
        Q("couplers", "Сцепки", "railways:track_coupler", 0, 1,
          text=["Четыре сцепки — четыре вагона. Составы разной длины на одном пути."],
          tasks=[give("railways:track_coupler", 4)],
          rewards=loot(("railways:track_coupler", 8), ("railways:buffer", 4), xp=80)),
        Q("semaphore", "Семафоры", "railways:semaphore", 0, 2,
          text=["Крылья вместо ламп. Работают как сигналы, выглядят как история."],
          tasks=[item("railways:semaphore", 4)], rewards=loot(("create:track_signal", 8), xp=60)),
        Q("crossing", "Переезд", "railways:generic_crossing", 1, 2,
          text=["Там, где дорога пересекает путь."],
          tasks=[item("railways:generic_crossing", 2)], rewards=loot(("railways:hazard_stripes_diagonal_on_black", 16), xp=40)),
        Q("fuel", "Дизель", "railways:fuel_tank", 0, 3,
          text=["Бак и дизельная труба. Поезд без угля."],
          tasks=[item("railways:fuel_tank", 2), item("railways:smokestack_diesel")],
          rewards=loot(("immersiveengineering:biodiesel_bucket", 4), xp=100)),
        Q("depot", "Депо", "railways:handcar", 0, 4,
          text=["Три состава с расписаниями, дрезина для осмотра пути, кондуктор "
                "на каждом. Сдайте четыре фуражки — у вас есть штат."],
          tasks=[item("create:schedule", 3), give("railways:conductor_cap", 4)],
          rewards=loot(("create:railway_casing", 16), ("railways:conductor_whistle", 2), xp=250)),
    ]),
)

chapter(
    "more_munitions", "more", 50, "Арсенал", "createbigcannons:powder_charge",
    "Боеприпасы, взрыватели и снабжение батареи",
    [],
    chain([
        Q("powder", "Пороховой погреб", "createbigcannons:packed_gunpowder", 0, 0,
          text=["Шестьдесят четыре заряда. Столько уходит на один хороший вечер."],
          tasks=[give("createbigcannons:powder_charge", 64)],
          rewards=loot(("createbigcannons:guncotton", 32), xp=80)),
        Q("fuzes", "Взрыватели", "createbigcannons:timed_fuze", 0, 1,
          text=["Ударный, инерционный, временной, дистанционный, проводной. "
                "По восемь каждого — на любой случай."],
          tasks=[give("createbigcannons:impact_fuze", 8), give("createbigcannons:timed_fuze", 8),
                 give("createbigcannons:proximity_fuze", 8)],
          rewards=loot(("createbigcannons:delayed_impact_fuze", 8), xp=100)),
        Q("shells", "Снарядный ряд", "createbigcannons:shrapnel_shell", 0, 2,
          text=["Шрапнель, дым, жидкость. Не всё должно взрываться."],
          tasks=[give("createbigcannons:shrapnel_shell", 8), give("createbigcannons:smoke_shell", 8),
                 give("createbigcannons:fluid_shell", 4)],
          rewards=loot(("createbigcannons:he_shell", 16), xp=120)),
        Q("belt", "Лента", "createbigcannons:autocannon_cartridge", 0, 3,
          text=["Сто двадцать восемь патронов и контейнер. Автопушка ест быстро."],
          tasks=[give("createbigcannons:autocannon_cartridge", 128), item("createbigcannons:autocannon_ammo_container", 2)],
          rewards=loot(("createbigcannons:tracer_tip", 32), xp=150)),
        Q("mg", "Пулемёт", "createbigcannons:machine_gun_round", 1, 3,
          text=["Ещё быстрее. Ещё меньше калибр."],
          tasks=[give("createbigcannons:machine_gun_round", 64)],
          rewards=loot(("createbigcannons:machine_gun_round", 128), xp=100)),
        Q("supply", "Снабжение батареи", "create:redstone_requester", 0, 4,
          text=["Запросчик заказывает заряды и снаряды со склада, фрогпорт приносит, "
                "заряжающий досылает. Батарея стреляет, пока есть порох на складе."],
          tasks=[item("create:redstone_requester"), item("createbigcannons:cannon_loader", 2), item("create:package_frogport", 2)],
          rewards=loot(("createbigcannons:cannon_mount", 1), xp=250)),
    ]),
)

chapter(
    "more_et_side", "more", 60, "Побочные тропы", E + "raccoon_flag",
    "То в Eternal Tales, что не ведёт к Унахзаалу, но стоит времени",
    [],
    [
        Q("raccoons", "Еноты", E + "raccoon_flag", 0, 0,
          text=["Все виды. Печенье в награду — от них же."],
          tasks=[adv(E + "tame_all_the_types_of_raccoons"), adv(E + "pet_the_raccoon")],
          rewards=loot((E + "white_chocolate_chip_cookie", 16), xp=150)),
        Q("tarkos", "Тарко", E + "fermented_tarantula_eye", 1, 0,
          text=["Доисторический оркестр."],
          tasks=[adv(E + "tame_all_the_types_of_tarkos")], rewards=loot(xp=150)),
        Q("chests", "Четыре сундука", E + "sorcery_chest", 2, 0,
          text=["Копательный, рыбацкий, садовый, колдовской — каждый навык оставляет "
                "сундук."],
          tasks=[adv(E + "get_digging_chest"), adv(E + "get_fishing_chest"), adv(E + "get_growing_chest"),
                 adv(E + "get_sorcery_chest")],
          rewards=loot((E + "ancient_coin", 16), xp=200)),
        Q("lamps", "Свет ночи", E + "soul_lava_lamp", 0, 1,
          text=["Все лава-лампы. Уютно."],
          tasks=[adv(E + "get_all_of_the_lava_lamps")], rewards=loot((E + "ender_lamp", 4), xp=100)),
        Q("music", "Коллекционер", E + "ruby_record", 1, 1,
          text=["Все пластинки мода. Тридцать восемь."],
          tasks=[adv(E + "get_all_the_mod_music_discs")], rewards=loot(("minecraft:jukebox", 2), xp=300)),
        Q("blue_moon", "Синяя луна", E + "blue_paste", 2, 1,
          text=["Пережить ночь слизней."],
          tasks=[adv(E + "stay_alive_during_blue_moon")], rewards=loot(("minecraft:slime_block", 16), xp=100)),
        Q("clown", "Цирк", E + "clown_armor_helmet", 0, 2,
          text=["Клоунская луна. Не смешно."],
          tasks=[adv(E + "stay_alive_during_clown_moon")], rewards=loot((E + "clown_armor_helmet", 1), xp=150)),
        Q("crabs", "Крабсапокалипсис", E + "crabsapocalypse_banner", 1, 2,
          text=["Они идут."],
          tasks=[adv(E + "pass_the_crabsapocalypse")], rewards=loot((E + "crabsburger", 16), xp=200)),
        Q("arky", "Арки", E + "ach_arky_item", 2, 2,
          text=["Красивый енот и его костюм."],
          tasks=[adv(E + "summon_arky"), adv(E + "get_any_fursuit")], rewards=loot(xp=150)),
        Q("gravicycle", "Гравицикл", E + "arkemer_gravicycle_item", 0, 3,
          text=["Собрать, разогнать до предела, не разбиться."],
          tasks=[adv(E + "make_arkemer_gravicycle"), adv(E + "accelerate_gravicycle_to_the_maximum")],
          rewards=loot((E + "gravicycle_acceleration_modifier", 1), xp=250)),
        Q("bomb", "Королевский бум", E + "atomic_bomb", 1, 3,
          text=["Атомная бомба Eternal Tales. Подальше от базы. Ещё дальше."],
          tasks=[adv(E + "blow_atomic_bomb")], rewards=loot(("minecraft:tnt", 64), xp=300)),
        Q("darwin", "Премия Дарвина", E + "unahzaal_pancakes", 2, 3,
          text=["Умереть всеми тремя глупыми способами. Книга не осуждает."],
          tasks=[adv(E + "die_by_all_3_stupid_ways")], rewards=loot((E + "unahzaal_pancakes", 1), xp=50)),
    ],
)

chapter(
    "more_home", "more", 70, "Дом", "handcrafted:bench",
    "Уют как отдельная дисциплина",
    [],
    chain([
        Q("bed", "Спальня", "minecraft:red_bed", 0, 0,
          text=["Кровать, тумба, лампа, ковёр. Handcrafted и Refurbished — на выбор."],
          tasks=[item("minecraft:red_bed"), item("handcrafted:blue_cushion", 2), item("refurbished_furniture:bath")],
          rewards=loot(("handcrafted:white_sheet", 4), xp=40)),
        Q("kitchen", "Кухня", "refurbished_furniture:computer", 0, 1,
          text=["Раковина, шкафы, холодильник, тостер. Всё работает."],
          tasks=[check("Собрать кухню из Refurbished Furniture")], rewards=loot(("minecraft:bread", 16), xp=40)),
        Q("workshop", "Мастерская", "domum_ornamentum:architectscutter", 0, 2,
          text=["Резак архитектора, верстак плотника Furnicraft, схематический стол Create. "
                "Место, где делают дом."],
          tasks=[item("domum_ornamentum:architectscutter"), item("create:schematic_table")],
          rewards=loot(("domum_ornamentum:dynamic_timberframe", 32), xp=60)),
        Q("garden", "Сад", "farmersdelight:tomato", 0, 3,
          text=["Грядки на богатой почве, горшок садовника Eternal Tales, клош IE. "
                "Три школы земледелия в одном дворе."],
          tasks=[item("farmersdelight:rich_soil", 16), item(E + "gardeners_pot"), item("immersiveengineering:cloche")],
          rewards=loot(("farmersdelight:organic_compost", 32), xp=100)),
        Q("hall", "Зал", "handcrafted:bear_trophy", 0, 4,
          text=["Трофеи боссов на стенах, пьедестал Сумеречного леса, витрина музея "
                "Eternal Tales. Дом, в котором есть что рассказать."],
          tasks=[item("twilightforest:trophy_pedestal"), item("handcrafted:bear_trophy"),
                 item("twilightforest:naga_trophy")],
          rewards=loot(("minecraft:item_frame", 32), xp=150)),
    ]),
)
