"""Практические ветки: оснащение → пробная партия → проверка эксплуатации.

Каждая работа имеет собственные входы, результат и проверку отказа. Отметка
эксплуатации всегда ручная: наличие предмета не доказывает работающую фабрику.
"""
from dsl import Q, item, check, loot

# chapter, key, anchor, RU/EN title, equipment, output, RU/EN setup, RU/EN test
PROJECTS = [
 ('create_andesite', 'bakery', 'millstone', ('Хлебная линия', 'Bread production'),
  [('create:millstone',1),('create:encased_fan',1),('create:depot',2)], [('minecraft:bread',16)],
  ('Смелите пшеницу в муку. Промывка муки даёт тесто; подготовьте отдельный участок выпечки. Укажите в JEI рецепт каждого перехода и разделите водяной и горячий потоки.',
   'Mill wheat into flour. Washing flour makes dough; prepare a separate baking stage. Inspect each transition in JEI and keep wet and hot airflow separate.'),
  ('Подайте пшеницу и проверьте, что мука, тесто и хлеб не смешиваются на возврате. Заполните выходной сундук и убедитесь, что готовый хлеб не выбрасывается и не попадает обратно в горячий поток.',
   'Feed wheat and check that flour, dough and bread stay on their intended routes. Fill the output chest and ensure finished bread is neither dropped nor sent back into hot airflow.')),
 ('create_andesite', 'sheets_line', 'press', ('Прокат без ручной подачи', 'Automatic sheet production'),
  [('create:mechanical_press',1),('create:belt_connector',2),('create:andesite_funnel',2)], [('create:iron_sheet',32)],
  ('Свяжите сундук со слитками, пресс и выходной сундук лентой. Настройте направление воронок и оставьте место для обслуживания пресса.',
   'Connect an ingot chest, press and output chest with a belt. Set funnel directions and leave access to the press.'),
  ('Пропустите пробную партию, затем перекройте подачу вращения. После включения линия должна продолжить обработку без ручной перестановки предметов.',
   'Process a test batch, then stop rotation. After restarting, the line should resume without manually moving items.')),
 ('create_brass', 'assembly_line', 'precision', ('Контур последовательной сборки', 'Sequenced assembly loop'),
  [('create:deployer',3),('create:brass_funnel',2),('create:belt_connector',3)], [('create:precision_mechanism',8)],
  ('Разделите входы трёх деплойеров: малая шестерня, большая шестерня, самородок железа. Возвращайте незавершённые механизмы на начало, а готовые изделия и побочные результаты выводите отдельно.',
   'Separate the three deployer inputs: small cogwheels, large cogwheels and iron nuggets. Loop unfinished mechanisms and route finished products and byproducts out separately.'),
  ('Временно уберите железные самородки, затем верните их. Проверьте, что очередь заготовок возобновилась, а готовый механизм не отправляется на шестой цикл.',
   'Temporarily remove iron nuggets, then restore them. Check that queued assemblies resume and finished mechanisms are not sent around for a sixth cycle.')),
 ('create_fluids', 'water_service', 'pump', ('Водоснабжение мастерской', 'Workshop water supply'),
  [('create:mechanical_pump',1),('create:fluid_pipe',8),('create:fluid_tank',4)], [('create:fluid_valve',1)],
  ('Соедините источник воды, насос и буферный бак. Выделите доступный участок трубы под клапан: так можно обслуживать потребителя без разборки всей сети.',
   'Connect a water source, pump and buffer tank. Leave an accessible pipe segment for a valve so a consumer can be serviced without dismantling the network.'),
  ('Откройте и закройте клапан, наблюдая за уровнем бака и потребителем. Убедитесь, что направление насоса соответствует потоку и вода возвращается после запуска вращения.',
   'Open and close the valve while watching the tank and consumer. Verify pump direction and recovery after rotation restarts.')),
 ('create_trains', 'freight', 'train', ('Грузовой маршрут', 'Freight route'),
  [('create:track_station',2),('create:portable_storage_interface',2)], [('create:schedule',1)],
  ('Сделайте две станции: погрузку и разгрузку. Настройте расписание и совместите переносные интерфейсы стоящего состава и платформы.',
   'Build loading and unloading stations. Configure a schedule and align the stationary train’s portable storage interface with the platform interface.'),
  ('Отправьте поезд с небольшой партией и дождитесь возвращения. Проверьте разгрузку, условие отправления и поведение при пустом погрузочном складе.',
   'Send a small shipment and wait for the train to return. Check unloading, departure conditions and an empty loading warehouse.')),
 ('ie_start', 'steel_service', 'blast', ('Снабжение сталью', 'Steel supply'),
  [('immersiveengineering:hammer',1)], [('immersiveengineering:ingot_steel',16)],
  ('Подготовьте кокс и железо для доменной печи. Разместите входное сырьё и готовую сталь отдельно; оставьте место для шлака и креозота от коксовой печи.',
   'Prepare coke and iron for the blast furnace. Separate raw materials from finished steel and leave storage for slag and coke-oven creosote.'),
  ('Пройдите полный цикл от угля до стали. Проверьте, что накопление креозота и шлака не блокирует следующую партию.',
   'Run a complete coal-to-steel cycle. Check that creosote and slag accumulation cannot block the next batch.')),
 ('mek_start', 'steel_line', 'steel', ('Два прохода инфузии', 'Two infusion passes'),
  [('mekanism:metallurgic_infuser',2),('mekanism:energized_smelter',1)], [('mekanism:ingot_steel',16)],
  ('Первый инфузер превращает железо в обогащённое железо, второй — в стальную пыль. Обоим нужен углерод. Пыль направьте в электрическую печь.',
   'The first infuser makes enriched iron; the second makes steel dust. Supply carbon to both and send the dust to an energized smelter.'),
  ('Проверьте отдельную подачу углерода и основного сырья. Остановите один из входов, затем восстановите его: линия должна продолжить работу без смешивания промежуточных материалов.',
   'Check separate carbon and main-material inputs. Interrupt one input and restore it; the line should resume without mixing intermediate materials.')),
 ('mek_ore', 'ore_line', 'enrichment', ('Участок обогащения', 'Enrichment workshop'),
  [('mekanism:enrichment_chamber',1),('mekanism:energized_smelter',1)], [('minecraft:iron_ingot',16)],
  ('Соедините обогатитель с печью и настройте стороны машин. Выберите в JEI рецепт именно вашего сырья: блоки руды и сырое железо дают разный выход.',
   'Connect an enrichment chamber to a smelter and configure their sides. Select the JEI recipe for your actual material: ore blocks and raw iron have different yields.'),
  ('Посчитайте вход и выход пробной партии. Затем заполните конечный сундук и убедитесь, что промежуточная пыль сохраняется, а не теряется.',
   'Count test-batch inputs and outputs. Then fill the destination chest and verify that intermediate dust is retained.')),
 ('rs_autocraft', 'processor_line', 'autocrafter', ('Процессоры по запросу', 'Processors on demand'),
  [('refinedstorage:autocrafter',1),('refinedstorage:importer',1)], [('refinedstorage:advanced_processor',8)],
  ('Запишите шаблон заготовки продвинутого процессора и отдельный шаблон её обжига. Нужны алмаз, кремний, красная пыль и связка процессора. Верните результат печи в сеть.',
   'Encode a raw advanced processor pattern and a separate smelting pattern. Supply diamond, silicon, redstone and processor binding. Return the furnace output to the network.'),
  ('Закажите восемь процессоров из интерфейса сети. Сверьте список недостающих материалов; после пополнения заказ должен завершиться и вернуть все восемь изделий.',
   'Request eight processors from the network. Inspect missing materials; after supplying them the job should complete and return all eight products.')),
 ('mc_production', 'timber_service', 'lumberjack', ('Дерево для строителя', 'Timber for builders'),
  [('minecolonies:blockhutlumberjack',1),('minecolonies:blockhutwarehouse',1)], [('minecraft:oak_log',32)],
  ('Выделите лесорубу рабочую зону и обеспечьте инструментами. Настройте склад и курьера так, чтобы древесина попадала в систему запросов строителя.',
   'Assign a work area and tools to the forester. Configure a warehouse and courier so timber reaches the builder’s request system.'),
  ('Создайте строительный запрос на древесину. Проследите путь от работника через склад до строителя; отдельно проверьте нехватку инструмента и доступность маршрута.',
   'Create a construction request for timber. Trace it from worker through warehouse to builder; check tool supply and path access.')),
 ('magic_botania', 'mana_service', 'manasteel', ('Устойчивая подача маны', 'Sustained mana supply'),
  [('botania:mana_pool',1),('botania:mana_spreader',1)], [('botania:manasteel_ingot',8)],
  ('Свяжите генерирующий цветок, распространитель и бассейн. Обеспечьте цветку его ресурс, а распространителю — свободную линию передачи.',
   'Bind a generating flower, spreader and pool. Supply the flower’s required resource and leave a clear mana path.'),
  ('Изготовьте манасталь, затем проверьте восстановление маны в бассейне. Одна заполненная ёмкость не означает устойчивое производство: источник должен продолжать работать.',
   'Make manasteel, then verify that the pool recovers its mana. A single full pool is not sustained production; the source must keep working.')),
 ('magic_ars', 'source_service', 'source', ('Источник для ритуалов', 'Source for rituals'),
  [('ars_nouveau:source_jar',1)], [('ars_nouveau:source_gem',16)],
  ('Выберите доступный генератор Источника и поставьте рядом накопитель. Обеспечьте генератор подходящей активностью или ресурсом по дневнику Ars Nouveau.',
   'Choose an available Source generator and place a jar nearby. Supply the activity or resource described in the Ars Nouveau notebook.'),
  ('Запустите потребитель Источника и наблюдайте расход, а затем восстановление запаса. Проверьте радиус действия и привязки реле, если передача не идёт.',
   'Run a Source consumer and observe consumption followed by recovery. Check range and relay bindings if transfer fails.')),
 ('magic_agriculture', 'essence_service', 'first_seeds', ('Урожай как сырьё', 'Crops as materials'),
  [('mysticalagriculture:inferium_seeds',1)], [('mysticalagriculture:inferium_essence',32)],
  ('Посадите семена инфериума на подходящей грядке. Организуйте сбор так, чтобы сохранять посадку, а эссенцию направляйте в отдельное хранилище.',
   'Plant inferium seeds on suitable farmland. Harvest while preserving the planting and store essence separately.'),
  ('Проверьте два последовательных урожая. После первого сбора грядка должна оставаться рабочей; переполнение склада не должно уничтожать нужные семена.',
   'Check two consecutive harvests. The plot must remain operational after the first; a full store must not destroy required seeds.')),
 ('fd_kitchen', 'food_service', 'pot', ('Кухня для экспедиции', 'Expedition kitchen'),
  [('farmersdelight:cooking_pot',1),('minecraft:bowl',8)], [('minecraft:bread',16)],
  ('Поставьте котёл над подходящим источником тепла. Выберите рецепт из имеющихся продуктов и подготовьте тару, если она нужна для выдачи блюда. Хлеб оставьте резервным пайком.',
   'Place the cooking pot above a suitable heat source. Select a recipe using available ingredients and prepare any required serving containers. Keep bread as a backup ration.'),
  ('Приготовьте блюдо и пополните ингредиенты на вторую партию. Проверьте, что нехватка мисок или выходного места не останавливает кухню незаметно.',
   'Cook a meal and restock for a second batch. Check that missing bowls or output space cannot silently stall the kitchen.')),
 ('space_ground', 'launch_service', 'checklist', ('Пусковой комплекс', 'Launch operations'),
  [('ad_astra:tier_1_rocket',1)], [('minecraft:iron_ingot',32)],
  ('Перед вылетом подготовьте топливо, кислород, питание и материалы для обратного пути. Железо в этой цели — резерв экспедиции, а не доказательство готовности кислородной системы.',
   'Before launch, prepare fuel, oxygen, power and return-trip materials. Iron in this objective is expedition reserve, not proof that life support works.'),
  ('Проверьте запас кислорода в скафандре, топливо ракеты и место посадки. Убедитесь, что обратный вылет возможен без ресурсов, которые ещё предстоит добыть.',
   'Check suit oxygen, rocket fuel and the landing plan. Ensure that the return flight does not depend on resources you have yet to obtain.')),
 ('aero_basics', 'flight_service', 'airship', ('Испытание дирижабля', 'Airship test flight'),
  [('minecraft:lead',2)], [('minecraft:compass',1)],
  ('Сначала испытайте лёгкую конструкцию возле базы. Отметьте точку возвращения и предусмотрите безопасную посадку; груз добавляйте после проверки управления.',
   'Test a light craft near your base first. Mark the return point and plan a safe landing; add cargo only after checking the controls.'),
  ('Взлетите, выполните разворот и вернитесь на исходную площадку. Проверьте поведение с грузом и остановку тяги перед дальним перелётом.',
   'Take off, turn and return to the original landing area. Test loaded handling and thrust shutdown before a long flight.')),
 ('tech2_pneumatic', 'pressure_service', 'chamber', ('Контроль давления', 'Pressure control'),
  [('pneumaticcraft:pressure_tube',8)], [('pneumaticcraft:ingot_iron_compressed',16)],
  ('Свяжите компрессор с камерой давления. Проверьте допустимый диапазон по интерфейсу и руководству; предусмотрите отключение компрессора до достижения предела оборудования.',
   'Connect the compressor to the pressure chamber. Check the supported pressure range in the interface and manual, and provide a cutoff before reaching equipment limits.'),
  ('Запустите один рецепт и проследите восстановление давления. Проверьте отключение компрессора при отсутствии расхода, не доводя систему до разрушения.',
   'Run one recipe and observe pressure recovery. Verify compressor cutoff with no demand, without pushing the system to destruction.')),
 ('cbc_foundry', 'range_service', 'shot', ('Приёмка орудия', 'Gun acceptance test'),
  [('minecraft:target',1)], [('minecraft:paper',1)],
  ('Подготовьте отдельное стрельбище с безопасным направлением огня. Убедитесь, что заряд, снаряд, затвор и последовательность заряжания соответствуют вашему орудию.',
   'Prepare a separate firing range with a clear firing direction. Verify that charge, projectile, breech and loading sequence match the gun.'),
  ('Выполните контрольный выстрел, затем повторите цикл заряжания. Запишите выбранный заряд и проверьте, что механизм возвращается в исходное положение.',
   'Fire a test shot and repeat the loading cycle. Record the chosen charge and check that the mechanism returns to its starting position.')),
]


def add_projects(chapters, translations):
    by_id = {c['id']: c for c in chapters}
    for cid, key, anchor, titles, equipment, output, setup, test in PROJECTS:
        c = by_id[cid]
        en = translations[cid]['quests']
        stages = [
            (key+'_setup', titles[0]+': оснащение', titles[1]+': equipment', [anchor],
             [item(i,n) for i,n in equipment],
             [setup[0], 'Соберите перечисленные компоненты. Следующий узел проверяет пробную партию, а отдельная ручная отметка — испытание установки.'],
             [setup[1], 'Collect the listed components. The next node checks a test batch; a separate manual objective records the installation test.']),
            (key+'_batch', titles[0]+': пробная партия', titles[1]+': test batch', [key+'_setup'],
             [item(i,n) for i,n in output],
             [setup[0], 'Получите указанную партию и возьмите её в обычный инвентарь. Предметы не расходуются. Учёт наличия не различает ручное и автоматическое производство.'],
             [setup[1], 'Obtain the listed batch and hold it in your regular inventory. Items are not consumed. Detection does not distinguish manual from automated production.']),
            (key+'_run', titles[0]+': проверка работы', titles[1]+': operation test', [key+'_batch'],
             [check('Проверка установки выполнена')],
             [test[0], 'Отметьте цель после проверки в мире. Кодекс не измеряет работу этой установки автоматически.'],
             [test[1], 'Mark the objective after checking the installation in the world. Codex does not measure its operation automatically.']),
        ]
        for qid, ru_title, en_title, deps, tasks, ru_text, en_text in stages:
            q = Q(qid, ru_title, equipment[0][0], 0, 0, deps=deps, text=ru_text,
                  tasks=tasks, rewards=loot(xp=25 if qid.endswith('_run') else 0),
                  shape='big' if qid.endswith('_run') else None, optional=True)
            c['quests'].append(q)
            en[qid] = {'title':en_title, 'text':en_text,
                       'tasks':['Manual: installation test completed'] if qid.endswith('_run') else []}
