# -*- coding: utf-8 -*-
EN = {
    "create_basics": {
        "title": "First Rotation", "subtitle": "Andesite alloy, shafts and sources of power",
        "intro": [
            "Create doesn't know the word 'energy'. It knows rotation: every shaft has speed and stress, and the whole art is adding one to the other so the machine doesn't stall.",
            "The first andesite alloy isn't a machine yet. It's a promise that in a few dozen hours your first train will leave from this very spot.",
        ],
        "quests": {
            "andesite": {"title": "Andesite Alloy", "text": ["It all starts with the ugliest stone in the game. Andesite with an iron or zinc nugget pressed to it becomes alloy — dull, gray and irreplaceable. Shafts, cogs, casings and half of what you'll build in the coming days come from it.", "Zinc is found in mountains and caves: raw zinc smelts to an ingot, the ingot goes into brass. Iron will do for now."], "rewards": ["Base material of the whole andesite age"]},
            "shaft": {"title": "Shaft", "text": ["A shaft does nothing. It passes things on: speed as is, direction as is, stress into the network's common pot. Everything else is built from such 'nothings'.", "Later a saw will cut shafts: six per alloy."]},
            "cogwheel": {"title": "Cogwheels", "text": ["Two cogs side by side spin opposite ways. A small one meshed with a large one halves the speed and doubles available stress; the reverse speeds up and drains. Create's entire gearbox fits in that rule.", "Two small cogs flush together jam the network. It's the first thing everyone breaks."]},
            "handcrank": {"title": "Hand Crank", "text": ["A handle you can turn. While you hold it, the mechanism lives. Gates, a lift, a single press at the start — your arms won't manage more, and more isn't needed yet."]},
            "waterwheel": {"title": "Water Wheel", "text": ["The first source that never tires. Eight RPM, a modest stress budget, but forever. Put it in a real flowing current — better yet a closed channel with sources — and the paddles catch water from every side."], "rewards": ["Constant rotation without fuel"]},
            "bigwheel": {"title": "Large Water Wheel", "text": ["Three by three, one item, noticeably stronger. Of the early sources it's the most honest: no coal, no attention, no surprises."]},
            "windmill": {"title": "Windmill", "text": ["A windmill bearing and sails around it. More area, more force; the cap is 128 sail blocks. Build the wings right on the bearing, click — and the structure tears free of the world and goes round.", "It's the first contraption of your life. There will be many."]},
            "sail": {"title": "Sails", "text": ["A frame covered in wool counts as a full sail. Fewer blocks — same thrust."]},
            "stress": {"title": "Stressometer and Speedometer", "text": ["Two needles without which Create is guesswork. The stressometer shows how much the network pulls and how much it can; the speedometer, how fast. Needle in the red — add a source or drop speed with cogs."]},
            "wrench": {"title": "Wrench", "text": ["Rotates, picks up with settings kept, gives hints. You won't put the wrench down until the very end — make two."]},
            "goggles": {"title": "Engineer's Goggles", "text": ["In the helmet slot. Speed, stress, tank contents — right in the block tooltip, no gauges."]},
            "ponder": {"title": "Ponder Scenes", "text": ["Every Create block has a tiny theater. Hover over an item, hold W — and the mechanism is assembled and started before your eyes, with commentary. It's the mod's best documentation, and the book sees when you watch."], "tasks": ["Open the Ponder scene for a cogwheel (W key)"]},
        },
    },
    "create_andesite": {
        "title": "Andesite Age", "subtitle": "First machines: press, millstone, saw, fan",
        "intro": ["Andesite casing is a door. Behind it: press, millstone, saw and fan — four machines that already double ore, cut planks, grind flour and smelt a stream. Not a factory yet. But no longer a workshop."],
        "quests": {
            "casing": {"title": "Andesite Casing", "text": ["Alloy and planks. A casing is a shell for a mechanism; at first made by hand, later stamped by the hundred."]},
            "press": {"title": "Mechanical Press", "text": ["The first machine that does something hands can't. An ingot becomes a sheet, a stack of planks a casing. The press strikes what's under it: a depot or a belt running below.", "Sheets are the consumable of everything to come. Iron, copper, gold, brass."]},
            "millstone": {"title": "Millstone", "text": ["Slow, modest, honest. Takes rotation only from above, grinds one item at a time and barely loads the network. But raw iron in it becomes crushed ore, and crushed ore smelts to one and a half ingots. The first ore doubling."], "rewards": ["Ore doubling at the early stage"]},
            "saw": {"title": "Mechanical Saw", "text": ["A horizontal saw cuts what rides the belt: planks, shafts, slabs. Vertical, it fells trees and — given rotation and room — becomes a sawmill that works while you sleep."]},
            "fan": {"title": "Encased Fan", "text": ["The fan pushes air. Through fire — it smelts. Through water — washes. Through lava — smokes. Through ice — freezes. The cheapest ore processing in the mod: a stream of crushed iron through a fan over fire, and ingots rain onto the belt."]},
            "belt": {"title": "Mechanical Belts", "text": ["Two shafts and a connector between them — a belt appears. Items ride it, creatures ride it, you ride it; press and saw work above it. Up to twenty blocks, no steeper than forty-five degrees.", "With belts, Create stops being a set of tools and becomes a line."]},
            "depot": {"title": "Depot and Funnels", "text": ["A depot is a one-item table: the press strikes over it, the saw cuts, the deployer works. A funnel puts in and takes out. The brass one can also choose."]},
            "chute": {"title": "Chutes", "text": ["Vertical. A plain chute drops down; a smart one filters and, given rotation, pulls up."]},
            "mixer": {"title": "Mechanical Mixer", "text": ["A mixer over a basin is already alchemy. Andesite alloy by the batch, brass, chocolate, concrete, dough: anything that needs 'mixing' happens here. The basin ejects the result itself if a depot stands below."], "rewards": ["Mass production of alloys"]},
            "blaze": {"title": "Blaze Burner", "text": ["For the basin to heat, fire must live under it — not any fire, a blaze. Take an empty burner to the Nether and catch the spirit with a click. Feed it coal for normal heat and blaze cake for white flame: each has its own recipes."]},
            "crafter_basic": {"title": "Mechanical Crafters", "text": ["A crafting table taken apart into cells. Each is a block; the wrench sets where cells pass contents, and at the end an item assembles. The only way to make precision mechanisms not one at a time but by the hundred."]},
            "ejector": {"title": "Weighted Ejector", "text": ["Flings an item or creature to a set point. Configured with the wrench. A catapult lift is an old and working joke."]},
        },
    },
    "create_kinetics": {
        "title": "Controlling Rotation", "subtitle": "Gearboxes, clutches, speed and its price",
        "intro": ["Speed in Create isn't free: faster means costlier in stress. This chapter is about the levers that turn, mute, accelerate and program rotation."],
        "quests": {
            "gearbox": {"title": "Gearbox", "text": ["Four sides, two directions. The vertical gearbox does the same along Y. Without it a shaft can't turn a corner."]},
            "clutch": {"title": "Clutch and Gearshift", "text": ["The clutch breaks transmission on a signal, the gearshift reverses it. 'Gearshift plus pulse' is the standard way to make a piston go back and forth."]},
            "chaindrive": {"title": "Chain Drives", "text": ["A row of shafts linked by chain spins as one. The adjustable drive doubles speed on the whole row on a signal."]},
            "sequenced": {"title": "Sequenced Gearshift", "text": ["A program of steps: turn this much, wait, reverse. Doors, lifts, assembly carousels — all on it."]},
            "rsc": {"title": "Rotation Speed Controller", "text": ["Sits under a large cog and tells it an exact speed, −256 to 256. Needs brass and settles most arguments with gearing for good."]},
            "flywheel": {"title": "Flywheel and Steam Engine", "text": ["A tank of water, burners beneath, engine on the side, flywheel at the output. The mid-game power plant looks exactly like this and hums accordingly."]},
            "logic": {"title": "Redstone Logic", "text": ["Repeater, pulse extender, timer, latch, analog lever, contact. All the automation — without kilometers of dust."]},
            "link": {"title": "Wireless Link", "text": ["Two items set a frequency, and the signal flies through air. The linked controller is a remote with buttons on chosen frequencies: a machine you run from another room."]},
            "stockpile": {"title": "Sensors", "text": ["The stockpile switch watches fullness, the content observer watches presence, the track observer watches for trains. Three ways to ask the world what it thinks."]},
            "display": {"title": "Displays", "text": ["The display link reads a machine and writes to a sign, board or nixie tubes. Counters, levels, departure boards — all of them."]},
        },
    },
    "create_fluids": {
        "title": "Fluids", "subtitle": "Pipes, pumps, valves and industrial pouring",
        "intro": ["A pipe in Create stores nothing. It's only a path. Count tanks and pumps, not meters of line; and the first thing that surprises a newcomer is that water in a pipe doesn't flow by itself."],
        "quests": {
            "pipe": {"title": "Fluid Pipes", "text": ["Glass ones show what's inside. Smart ones filter. A valve shuts on a signal. Plain ones just connect the ends."]},
            "pump": {"title": "Mechanical Pump", "text": ["The pump gives fluid direction and speed. Without it the network is a drawing. Direction changes with a wrench or a signal."]},
            "tank": {"title": "Fluid Tank", "text": ["Tanks merge into a reservoir of any size; the window shows the level. Taller means more."]},
            "hose": {"title": "Hose Pulley", "text": ["The hose drops into a lake and drinks it to the bottom. Or the reverse — fills it. A large enough body counts as infinite, and then it's an eternal source."], "rewards": ["Infinite water and industrial lava extraction"]},
            "spout": {"title": "Spout and Drain", "text": ["The spout pours onto an item — that's how blaze cakes are made and bottles filled. The drain pulls back out of buckets."]},
            "chocolate": {"title": "Chocolate and Honey", "text": ["Cocoa in a hot basin — chocolate. Honeycomb — honey. Not just food: honey goes into recipes, and chocolate berries are more filling than they look."]},
            "portable_fluid": {"title": "Portable Interface", "text": ["The contraption pulls up, interfaces dock — and fluid and items flow into the fixed network. That's how trains and drilling rigs unload."]},
        },
    },
    "create_copper": {
        "title": "Copper Age", "subtitle": "Steam, pressure and diving",
        "intro": ["Copper is steam. Copper casing opens boilers, engines and the gear that lets you go where you couldn't before."],
        "quests": {
            "copper_casing": {"title": "Copper Casing", "text": ["Copper sheets and planks. Needed for encased pipes, the hose pulley and all steam tech."]},
            "boiler": {"title": "Steam Boiler", "text": ["A tank of water, burners beneath, engines on the sides. A boiler has a level — one to eighteen — growing with volume, burner count and fire quality. Each engine takes its share and spins a shaft. Nothing in the mod gives this much force from so small a footprint."], "rewards": ["Thousands of stress units from a small pad"]},
            "whistle": {"title": "Steam Whistle", "text": ["Pitch set with extensions. Melodies are built from whistles — and the train horn heard beyond the hill."]},
            "backtank": {"title": "Copper Backtank", "text": ["The backtank stores compressed air while a shaft spins it, and hands it to a helmet underwater. Netherite holds more and doesn't fear lava."]},
            "diving": {"title": "Diving Gear", "text": ["The helmet breathes from the tank, the boots hold you on the bottom. The ocean stops being a wall."]},
            "netherite_diving": {"title": "Netherite Set", "text": ["In it you walk the floor of Nether lava lakes. Slowly, but you walk."]},
        },
    },
    "create_brass": {
        "title": "Brass Age", "subtitle": "Brass, crushing wheels and smart automation",
        "intro": ["Brass is the border between 'did it by hand' and 'did it once and for all'. Everything that filters, counts, chooses and decides needs it. Before brass Create is a set of clever gadgets; after — a factory."],
        "quests": {
            "brass": {"title": "Brass", "text": ["Copper and zinc in a hot basin. Normal heat is enough. Everything that can think is made of this yellow metal."]},
            "brass_casing": {"title": "Brass Casing", "text": ["The base of filtering funnels, logic tunnels and machines that decide for themselves."]},
            "crushing": {"title": "Crushing Wheels", "text": ["Two wheels turning toward each other. Everything that falls between is ground — ore, stone, a careless player. Unlike the millstone, the wheels eat a stream, and that's the main ore doubling for the whole mid-game."], "rewards": ["Industrial ore doubling"]},
            "brass_funnel": {"title": "Brass Funnels and Tunnels", "text": ["The funnel picks by item, the tunnel splits a stream evenly, in turn or by filter. The attribute filter understands words like 'food', 'tool', 'enchanted' — and sorts by meaning."]},
            "deployer": {"title": "Deployer", "text": ["A mechanical hand with one gesture: click, hit, plant, milk. On a contraption — the heart of any farm; on a line — an assembler that never gets bored."]},
            "arm": {"title": "Mechanical Arm", "text": ["The wrench marks where to take from and where to put — and the arm carries, filtering at each point. One manipulator instead of a dozen funnels."]},
            "precision": {"title": "Precision Mechanism", "text": ["Gold sheet, rods, cogs — and five crafters in a ring with deployers. The mechanism only assembles on a line, and it's the first thing in Create you can't make without Create. From here on everything needs it: schedules, radars, late automation."], "rewards": ["Pass into Create's late automation"]},
            "vault": {"title": "Item Vault", "text": ["A cube of blocks — one inventory for all: funnels, arms, packagers and, later, the Refined Storage network."]},
            "chromatic": {"title": "Chromatics", "text": ["Chromatic compound under light — Refined Radiance; in the dark under pressure — Shadow Steel. Materials for top-tier casings and for those who like pretty things."]},
        },
    },
    "create_contraptions": {
        "title": "Contraptions", "subtitle": "Moving structures: bearings, pistons, pulleys",
        "intro": ["A contraption is a piece of the world that Create tears off and moves as one. A bridge that turns. A drill that drives. A house that spins on an axis if you felt like it. The rules are the same everywhere: assemble, apply rotation, let go."],
        "quests": {
            "glue": {"title": "Super Glue and Chassis", "text": ["Glue binds blocks into a group. A linear chassis pulls along an axis, a radial one in a circle; range set with the wrench."]},
            "piston": {"title": "Mechanical Piston", "text": ["Moves in a straight line the length of the poles. Sticky brings it back. Gates, bridges, sliding walls."]},
            "pulley": {"title": "Rope Pulley", "text": ["Lowers and raises. A mine lift, a rig lowered into the abyss."]},
            "elevator": {"title": "Elevator", "text": ["A real elevator: a contact on each floor, a sign with the name, a button. You wait for the car — and it comes."]},
            "bearing": {"title": "Mechanical Bearing", "text": ["Spins a structure around itself. Carousel, swing bridge, windmill, circular assembly line."]},
            "clockwork": {"title": "Clockwork Bearing", "text": ["One turn per day. A tower clock, a shadow crawling across the square — pure decoration, and no less lovely for it."]},
            "tools_contraption": {"title": "Tools on a Contraption", "text": ["The drill breaks, the saw fells, the plough tills and collects, the harvester reaps, the roller lays road. All of it works only in motion — and in motion never tires."]},
            "cart": {"title": "Cart Contraptions", "text": ["The assembler turns a build over a rail into a riding minecart. Coupling makes two carts a train long before real trains."]},
            "gantry": {"title": "Gantry System", "text": ["A carriage rides a shaft-rail and drags anything behind it. Chunk-sized quarries start here."]},
            "controls": {"title": "Contraption Controls", "text": ["The controls switch parts of the machine from inside. The seat sits you down, the train controls give you a train. A machine you ride is a different kind of relationship."]},
        },
    },
    "create_packages": {
        "title": "Packages and Factory", "subtitle": "Create 6 logistics: boxes, stock and orders",
        "intro": ["Create's sixth version brought the post. Items are packed into cardboard boxes, boxes ride chains and belts, and the stock answers orders without asking who ordered. There's something of an old post station in it — and something of a factory that knows what it's missing."],
        "quests": {
            "cardboard": {"title": "Cardboard", "text": ["Paper under the press. From cardboard — packages, package filters and armor mobs don't notice you in. The last part isn't a joke."]},
            "packager": {"title": "Packager", "text": ["Takes from an inventory, puts in a box, writes the address. On order or on request. The repackager later reassembles contents."]},
            "frogport": {"title": "Frogport", "text": ["A frog on a chain. Catches packages, sends packages, unloads into a chest. It croaks if you listen."]},
            "chain_conveyor": {"title": "Chain Conveyor", "text": ["A chain between nodes over any distance. Boxes ride it — and you, if you grab on. The cheapest way to link distant builds."]},
            "stock_link": {"title": "Stock Link", "text": ["Hangs on a storage and reports to the ticker what's inside."]},
            "ticker": {"title": "Stock Ticker", "text": ["The whole stock in one window. Ordered — packagers packed, frogs delivered. The shopping list remembers what you order every time."], "rewards": ["A single pickup point for any materials"]},
            "requester": {"title": "Requester", "text": ["A signal — and the stock sends a set. A machine that orders its own raw materials."]},
            "factory_gauge": {"title": "Factory Gauge", "text": ["The gauge knows what should lie at the output and how much. If it's short, it orders the missing from neighboring gauges, and they from theirs. A factory built on gauges doesn't wait for commands: it plans."], "rewards": ["Self-planning production"]},
            "shop": {"title": "Shop", "text": ["Table cloth, bell, ticker — and it's a store. On servers, markets grow from these."]},
            "postbox": {"title": "Postboxes", "text": ["The address is written on the package. A box with that address accepts it — wherever it stands."]},
        },
    },
    "create_trains": {
        "title": "Trains", "subtitle": "Tracks, stations, schedules and Steam 'n' Rails",
        "intro": ["A Create train doesn't ride the rails — it lives on them. It has a schedule, a conductor, signals that won't let two trains on one section, and a board it's awaited on at the station.", "The first line usually links base to mine. The last runs past the horizon just because it can."],
        "quests": {
            "sturdy": {"title": "Sturdy Sheet", "text": ["Obsidian through press and millstone. Material for what must bear a train's weight."]},
            "railway_casing": {"title": "Railway Casing", "text": ["Stations, signals, bogeys, controls. Everything railway starts with it."]},
            "track": {"title": "Tracks", "text": ["Two points — and Create lays the curve, climb or loop between them. Tracks can run through air; supports grow on their own. Thirty-two for the first line to the mine."]},
            "station": {"title": "Station", "text": ["Here the train is assembled and here it stops. Bogeys on the track, body on top, the 'Assemble' button — and the train exists."]},
            "bogey": {"title": "Bogeys", "text": ["Small for wagons, large for the locomotive. Steam 'n' Rails adds double-axle and narrow-gauge."]},
            "train": {"title": "First Train", "text": ["A locomotive needs power aboard: a boiler with an engine or, later, an electric motor. Controls are yours, the seat is the driver's. The first time the train moves with you inside, you'll understand what all this was for."], "rewards": ["Your own railway"]},
            "schedule": {"title": "Schedule", "text": ["Go there, wait for loading, wait a minute, go back. Conditions — inventory, signal, time of day. Hand the schedule to a conductor — and the train stops needing you."]},
            "signals": {"title": "Signals", "text": ["A signal divides the track into blocks and keeps a second train out of an occupied one. On a single-track line with opposing traffic, without them there'll be a catastrophe — a beautiful one, but a catastrophe."]},
            "board": {"title": "Board", "text": ["Train, direction, arrival time. Passengers like it."]},
            "snr_coupler": {"title": "Steam 'n' Rails: Couplers", "text": ["Screw, knuckle, link-and-pin. Trains uncouple on the move, buffers absorb the bump, headstocks make wagon ends look like wagon ends."]},
            "snr_conductor": {"title": "Conductor", "text": ["A cap on a villager — and he drives the train by schedule. The whistle calls the train to the nearest station, like a taxi."]},
            "snr_style": {"title": "Locomotive Styling", "text": ["Smokestacks, boilers, smokeboxes, locometal in every color, hazard stripes, paint in pitchers. None of it is needed. All of it is wanted."]},
            "snr_handcar": {"title": "Handcar", "text": ["Pump the lever — you go. No boiler, no schedule, no dignity."]},
        },
    },
    "create_tools": {
        "title": "Gear and Schematics", "subtitle": "Create tools and building from blueprints",
        "intro": [],
        "quests": {
            "extendo": {"title": "Extendo Grip", "text": ["Your arms get longer. Two grips — longer still."]},
            "potato": {"title": "Potato Cannon", "text": ["Shoots what grows. Potatoes hit, beetroot stains, fire noodles burn. With a backtank — in bursts."]},
            "symmetry": {"title": "Wand of Symmetry", "text": ["Place a block on the left — it appears on the right. Symmetrical buildings in half the time."]},
            "schematic": {"title": "Schematics", "text": ["The quill outlines an area and saves it to a file. The table loads the file into an empty schematic. A building becomes an item."]},
            "cannon": {"title": "Schematicannon", "text": ["The cannon fires blocks from a chest by blueprint — and on empty ground rises a building you built once somewhere else. Gunpowder as fuel adds gravity to the affair."], "rewards": ["Automatic construction of any saved build"]},
            "blueprint": {"title": "Crafting Blueprint", "text": ["A recipe on the wall. Click — assembled from your inventory."]},
            "toolbox": {"title": "Toolbox", "text": ["Eight item sets handed to the hotbar by hotkey to everyone nearby."]},
            "worldshaper": {"title": "Worldshaper", "text": ["A creative terrain tool. Not in survival; worth knowing about."], "tasks": ["Read"]},
        },
    },
    "create_world": {
        "title": "Create in the World", "subtitle": "Structures, decor and small add-ons",
        "intro": [],
        "quests": {
            "arise": {"title": "Create: Structures Arise", "text": ["Abandoned factories, workshops, mines with working mechanisms. Someone built here before you — and left, leaving blueprints in chests."], "tasks": ["Find a Create structure in the world"]},
            "rustic": {"title": "Create: Rustic Structures", "text": ["Mills, sawmills, farmyards. Village Create, fitted into Terralith's hills."], "tasks": ["Find a rustic Create structure"]},
            "oplenty": {"title": "CreateOPlenty", "text": ["Sandpaper from BOP sands, BOP stone and wood in Create machines."]},
            "stickywheels": {"title": "Sticky Wheels", "text": ["Sticky tires for Offroad: hold a slope, don't slip on ice."]},
            "deco": {"title": "Decorative Blocks", "text": ["Copper shingles in every stage of green, framed glass, girders, brackets, copycat blocks that take any look. Create knows how to be beautiful."]},
        },
    },
}
