# -*- coding: utf-8 -*-
EN = {
    "ca_electric": {
        "title": "Create Addition: Electricity", "subtitle": "Turning rotation into energy and back",
        "intro": ["The pack's three technologies speak different languages: Create in rotation, Immersive Engineering and Mekanism in energy. Create Addition is the translator. Without it three factories would stand side by side and never know of each other."],
        "quests": {
            "rolling": {"title": "Rolling Mill", "text": ["Ingot to rod, rod to wire. No wire, no spools; no spools, no cables."]},
            "wire": {"title": "Wire and Spools", "text": ["Copper conducts, gold better, electrum best of all. Wire on a spool becomes a cable strung between connectors."]},
            "electrum": {"title": "Electrum", "text": ["Gold with zinc in the mixer. The mod's best conductor and the material of an amulet that stores experience."]},
            "alternator": {"title": "Alternator", "text": ["A shaft goes in — energy comes out. Faster shaft, more energy and more stress. Water wheel, controller, alternator: the pack's first power plant fits on a table."], "rewards": ["First FE energy"]},
            "motor": {"title": "Electric Motor", "text": ["The reverse translation: energy into rotation at a set speed. A motor in a locomotive instead of a boiler — and the train charges at the station like a phone."]},
            "connector": {"title": "Connectors and Cables", "text": ["A connector on the machine, a cable between connectors. Large carries more current, the light one powers lamps, the relay breaks the circuit on a signal."]},
            "accumulator": {"title": "Accumulator", "text": ["Stores. The modular one grows into a battery of any size."]},
            "burner": {"title": "Liquid Blaze Burner", "text": ["A retired blaze: a burner on bioethanol or oil heats a basin just as well. Biomass from plants, pellets under the press, distillation — and fuel grows in the garden."]},
            "tesla": {"title": "Tesla Coil", "text": ["Lightning at everything alive nearby. Also charges items and turns sand to glass on a belt. Don't put it by the entrance."]},
            "digital": {"title": "Digital Adapter", "text": ["Reads a Create machine and speaks in numbers: level, speed, presence."]},
            "pei": {"title": "Portable Energy Interface", "text": ["Energy between a contraption and the grid. The train pulls up — charges — leaves."]},
        },
    },
    "aero_basics": {
        "title": "Create Aeronautics: Flight", "subtitle": "Real physics, airships and levitite",
        "intro": ["Create Aeronautics doesn't pretend. A structure here doesn't teleport between points — it flies: lists under weight, loses altitude when the burner dies, and crashes if the pilot forgot the ground is hard.", "Two more mods come with it: Create Simulated — sensors, ropes, physical mechanisms — and Create Offroad, which puts it all on wheels."],
        "quests": {
            "assembler": {"title": "Physics Assembler", "text": ["A click — and the build stops being part of the world. It gains mass, inertia and the ability to fall. Disassembled with the same block."], "rewards": ["Access to all physics tech"]},
            "levitite": {"title": "Levitite", "text": ["A material with negative mass. The blend brews in a basin from ender powder, is poured and sets into blocks that pull upward. Pearlescent — for heavy vessels."]},
            "envelope": {"title": "Airship Envelope", "text": ["A balloon. Its volume is the lift. An envelope with a shaft inside passes rotation through itself. Sixteen colors."]},
            "burner_aero": {"title": "Adjustable Burner", "text": ["Heats the air in the envelope. Hotter fire — higher. A signal is the regulator."]},
            "airship": {"title": "First Airship", "text": ["Gondola, envelope on top, burner, a steam vent for dumping, assembler. The first ascent is always crooked; the first flight over your own base is always silent."], "rewards": ["Your own flying vessel"]},
            "propeller": {"title": "Propellers", "text": ["Wooden light, andesite tough, smart changes pitch in flight. On a propeller bearing, on a shaft, forward."]},
            "gyro": {"title": "Gyroscopes", "text": ["Without a gyroscope the ship lists and one day flips. With one it stands in the air as if on a table."]},
            "goggles_aero": {"title": "Aviator's Goggles", "text": ["Altitude, speed, roll, pitch — on the glass."]},
            "sensors": {"title": "Sensors", "text": ["Altimeter, gimbal, optics, laser. Autopilot is assembled from these: the altimeter holds level, the gimbal evens the wings."]},
            "engine": {"title": "Portable Engine", "text": ["Rotation aboard, without a boiler or shafts from the ground."]},
            "docking": {"title": "Docking and Mooring", "text": ["A connector joins two vessels, a paired one is a hinge. Ropes tow and moor. An airship port — reality."]},
            "navigation": {"title": "Navigation Table", "text": ["Map, route, a typewriter with a program and a receiver. A ship that flies itself while you sleep in its hold."], "rewards": ["Autonomous flights along a route"]},
        },
    },
    "offroad": {
        "title": "Create Offroad: Ground Vehicles", "subtitle": "Wheels, suspension and all-terrain",
        "intro": [],
        "quests": {
            "wheel_mount": {"title": "Wheel Mount", "text": ["Wheel on axle, rotation on wheel. Four — a car."]},
            "tires": {"title": "Tires", "text": ["Small, regular, large, monstrous. Sticky versions — Sticky Wheels — hold slope and ice."]},
            "borehead": {"title": "Borehead", "text": ["A rock-cutting wheel on a physics chassis. The tunnel closes with darkness behind you."]},
            "vehicle": {"title": "First Vehicle", "text": ["Frame, four mounts with tires, engine, controls, a directional gearshift for steering — and the assembler. Across Terralith's hills on wheels."], "rewards": ["Ground transport with real physics"]},
        },
    },
    "cbc_foundry": {
        "title": "Big Cannons: Foundry", "subtitle": "Metals, molds and the first gun",
        "intro": ["Create Big Cannons is real artillery: barrels are cast from melt, bored, welded into sections, loaded with powder charges and shells, and block strength in the world truly counts on impact.", "Metals ascend: cast iron, bronze, steel, nethersteel. Better metal, bigger charge the barrel takes."],
        "quests": {
            "melting": {"title": "Melting Metal", "text": ["Metal melts in a Create basin under a foundry lid on high heat. Cast iron from iron and coal, bronze from copper and zinc, steel from iron with additives.", "Melt is stored in ordinary Create tanks and poured with a spout."]},
            "sand": {"title": "Casting Sand", "text": ["Foundry sand is the consumable for molds. Sand and clay."]},
            "cast": {"title": "Barrel Mold", "text": ["A mold is assembled from sections of different diameter (very small through very large). Pour melt, wait for it to set — a finished cast.", "The sections set the future gun's caliber."]},
            "drill": {"title": "Boring", "text": ["An unbored casting can't fire: it must be bored on a drilling rig. The rig is a contraption with a drill bit that travels along the barrel.", "Only after boring is the barrel usable."]},
            "barrel": {"title": "First Barrel", "text": ["Cast iron is the cheapest. It takes only weak charges, but enough to learn the mechanics.", "A barrel is assembled from sections: the chamber, several barrel sections and the end."]},
            "welder": {"title": "Welding Sections", "text": ["The welder joins sections into one gun. Without welding the shot tears the seam."]},
            "mount": {"title": "Mount and Carriage", "text": ["The cannon mount aims horizontally and vertically, driven by Create controls or a targeting controller.", "The fixed mount is cheaper but doesn't turn; the wheeled carriage is hauled by hand."]},
            "powder": {"title": "Powder Charge", "text": ["A charge is pressed powder in a casing. Charge count sets range and damage, but exceeding the barrel's limit bursts it.", "Guncotton and nitropowder are stronger than plain powder."]},
            "shot": {"title": "First Shot", "text": ["Loading order: charge, then projectile, then ignition (flint or redstone at the chamber).", "Solid shot pierces, grapeshot sprays, a stone ball is the cheapest."], "rewards": ["A working artillery piece"]},
            "loader": {"title": "Autoloading", "text": ["The cannon loader with a ram rod and worm automates the cycle: extract, clean, load, fire.", "A battery with autoloading fires continuously."]},
        },
    },
    "cbc_advanced": {
        "title": "Big Cannons: Heavy Ordnance", "subtitle": "Steel, autocannons and special shells",
        "intro": [],
        "quests": {
            "bronze": {"title": "Bronze", "text": ["Bronze barrels take a bigger charge than cast iron and wear slower."]},
            "steel": {"title": "Steel", "text": ["Steel guns are the mod's workhorse. Built-up barrels appear — several layers — taking maximum charges."]},
            "nethersteel": {"title": "Nethersteel", "text": ["Top of the line. Nethersteel barrels and screw breeches fire the heaviest charges without risk of bursting."]},
            "breech": {"title": "Breeches", "text": ["A muzzle-loader needs cleaning after every shot. The sliding breech loads from the rear, the quick-firing one uses cartridges."]},
            "shells": {"title": "Shells", "text": ["HE explodes, AP pierces, shrapnel covers infantry, smoke screens, fluid spills a tank's contents.", "Each shell takes a fuze: impact, inertia, timed, proximity or wired."]},
            "autocannon": {"title": "Autocannon", "text": ["The autocannon fires bursts of unitary cartridges. Needs a barrel, a breech with extractor and a recoil spring.", "Cartridges are assembled from cases, powder and rounds; the ammo container feeds the belt."], "rewards": ["Rapid-fire automatic weapon"]},
            "autoammo": {"title": "Autocannon Rounds", "text": ["AP, incendiary and flak rounds solve different problems. A tracer tip helps correct fire."]},
            "mortar": {"title": "Mortar", "text": ["Lobs at short range. Cheap and effective against fortifications."]},
            "armor": {"title": "Armor and Protection", "text": ["The armor inspection tool shows which block takes which charge. The gas mask protects from gas shells.", "Planning a fortification, check blocks with this tool — intuition lies here."]},
        },
    },
    "radar": {
        "title": "Create Radar: Targeting", "subtitle": "Detection, air defense and automatic aiming",
        "intro": ["Create Radar links artillery to electronics: radars find targets, controllers aim guns, IFF tells friend from foe."],
        "quests": {
            "plate": {"title": "Radar Plates", "text": ["The antenna is assembled from plates; more area, longer range. The dish is the compact option."]},
            "radar": {"title": "Radar", "text": ["The radar detects moving physics objects and creatures in its sector and passes coordinates over the data line."]},
            "datalink": {"title": "Data Link", "text": ["The data link connects radar, monitor and controllers. Filters (target, ident, network) weed out clutter."]},
            "iff": {"title": "Friend or Foe", "text": ["The transponder marks your object as friendly, the safe zone designator excludes an area from fire, the RWR warns you're being painted by someone else's radar."]},
            "controllers": {"title": "Targeting Controllers", "text": ["Auto yaw and pitch controllers aim the mount at a target from the radar. The fire controller gives the shot command with lead."], "rewards": ["An automatic turret"]},
            "guidance": {"title": "Shell Guidance", "text": ["The guided fuze and ARAD module steer a shell to a target or a radio source. The jammer breaks enemy guidance."]},
            "misc_radar": {"title": "Miscellany", "text": ["Binoculars zoom and highlight targets; the radio carries voice and signals over distance."]},
        },
    },
    "missiles": {
        "title": "Missiles", "subtitle": "CBC Aeronautics Missiles: guided rocket weapons",
        "intro": ["A small mod that stitches Big Cannons, Aeronautics and Radar together: a missile is a physics object with an engine, fins and a guidance system."],
        "quests": {
            "motor_rocket": {"title": "Rocket Motor", "text": ["The motor gives thrust to a physics object. More motors, more speed and less burn time."]},
            "fins": {"title": "Fins", "text": ["Actuator fins turn the missile in flight on commands from the guidance computer."]},
            "computer": {"title": "Guidance Computer", "text": ["The computer takes a target from the targeting interface or radar and steers the missile with the fins."]},
            "fuze_prox": {"title": "Proximity Fuze", "text": ["Detonates the warhead near an air target — the basis of anti-air missiles."]},
            "mount_missile": {"title": "Launcher", "text": ["The mount holds the missile until launch and releases on a signal. With a radar and fire controller it's a full SAM system."], "rewards": ["Guided missile weaponry"]},
        },
    },
}
