# -*- coding: utf-8 -*-
EN = {
    "et_intro": {
        "title": "Eternal Tales", "subtitle": "Journal, Eternal Town and notice boards",
        "intro": ["Eternal Tales begins quietly: with a journal, a town of musicians, a storyteller who knows more than he says. Nine dimensions come later — in the order someone else's war arranged them.", "The mod documents itself almost completely. Notice boards in Eternal Town explain every mechanic, and the journal keeps the quest list. This book only shows the order to read them in."],
        "quests": {
            "journal": {"title": "Journal", "text": ["A notebook for promises. Quests come from NPCs in Eternal Town and dimension settlements; the journal remembers conditions and rewards even when you've forgotten who asked."]},
            "town": {"title": "Eternal Town", "text": ["A town of musicians, built by one man for one girl. Here live Aeter, Miguel the Storyteller, trophy traders and a bard who plays for a coin. Everything starts here."], "tasks": ["The 'Musicians Town' quest"]},
            "notice": {"title": "Notice Board", "text": ["The board is the mod's textbook and the place level points are spent. Read them all: sorcery, archaeology, fishing, Darkness mode, crystal recipes — all described there, written by those who made it."]},
            "starter": {"title": "Starter Kit", "text": ["A chest with what helps on day one."]},
            "miguel": {"title": "Miguel the Storyteller", "text": ["He sells boss summons and knows the story of the burned village, Vivid and a girl named Eternity. Not everything he says is true. All of it matters."]},
            "bard": {"title": "Bard", "text": ["A coin — a song. You can take the guitar for yourself."]},
            "coins": {"title": "Coins", "text": ["Ancient and gold. The mod traders' currency, in chests and mob pockets."]},
            "quests_all": {"title": "All Quests", "text": ["Overworld, Nether, End, every dimension and the Aftermath line. Finish everything — and hear the story whole, from the first village to the last record."], "rewards": ["The complete Eternal Tales storyline"]},
        },
    },
    "et_skills": {
        "title": "Skills", "subtitle": "Nine skills and level points",
        "intro": ["Skills grow on their own — from what you do. Each new level of any of them gives a point you can put into any other via the board. So a digger becomes a sorcerer, and a sorcerer a fisherman if needed."],
        "quests": {
            "level": {"title": "Player Level", "text": ["Raise a skill — get a point. Spend a point — raise a skill. A circle that turns in your favor."]},
            "digging": {"title": "Digging", "text": ["From ore. Higher level — extra chunks more often."]},
            "slaying": {"title": "Slaying", "text": ["From mobs: points equal their health divided by twenty. Opens emblems."], "tasks": ["Raise the Slaying skill"]},
            "archery": {"title": "Archery", "text": ["From bows and thrown weapons. Opens the jewelry table and the archer's glove."]},
            "growing": {"title": "Growing", "text": ["From plants in the gardener's pot. From level five — water and fertilizer."]},
            "fishing": {"title": "Fishing and Catching", "text": ["Fishing — from rare fish; catching — from insects in the net. Insects become bait; the rarer the bug, the better the catch."]},
            "archaeology_skill": {"title": "Archaeology", "text": ["From brushing and from shredding blueprints."]},
            "speech": {"title": "Speech", "text": ["From trading. Discounts grow."], "tasks": ["Trade with an Eternal Tales merchant"]},
            "sorcery_skill": {"title": "Sorcery", "text": ["From rune stones, essences and artifacts. Without a sorcery level a dimension crystal won't assemble — that's the mod's main lock."]},
            "fear": {"title": "Fear", "text": ["Only in Eternal Darkness. From mobs under fear; gives speed, strength and night vision by level."]},
        },
    },
    "et_sorcery": {
        "title": "Sorcery", "subtitle": "Runes, essences, matrix and astral enchanting",
        "intro": ["Sorcery here is a craft. Runes drop from stones, stones stand in every world, and every world has its own rune. From runes brew essences, from essences — power."],
        "quests": {
            "runes": {"title": "Runes", "text": ["Rune stones are broken with a pickaxe; the Rune Prospector enchant multiplies drops. Forest, desert, nether, comet, eden — by world. The bag stores them."]},
            "cauldron": {"title": "Extraction Cauldron", "text": ["More than twenty runes — into the cauldron on soul sand, and out come essences: the currency that buys artifacts and charges the matrix."]},
            "matrix": {"title": "Runic Matrix", "text": ["The matrix lays runes on armor and weapons. Runic armor is what you put into it."]},
            "books": {"title": "Spell Books", "text": ["Glowing, dolphin's grace, portal disease and dozens more — single-use and reusable."]},
            "astral": {"title": "Astral Enchanter", "text": ["Enchantments the regular table lacks, and levels above the usual cap."]},
            "rituals": {"title": "Rituals", "text": ["Activators summon spirits, bring luck, cast curses, drop stars. Blueprints — at the jewelry table; copies — at the printer."]},
            "altars": {"title": "Altars", "text": ["Arei, Arla, Arahulum, Haciru, Hirots, Ikkorh, Enicrih, bloody, purgatory, hellish, royal. Each calls its own."]},
        },
    },
    "et_archaeology": {
        "title": "Archaeology", "subtitle": "Brushes, blueprints, vases and totems",
        "intro": [],
        "quests": {
            "brush": {"title": "Brushes", "text": ["Venetium — the start; truadamantite — the limit. Suspicious blocks wait in every world."]},
            "sherds": {"title": "Sherds and Vases", "text": ["From sherds — neodymium and uranium vases. Uranium ones glow, and not as a joke."]},
            "blueprints": {"title": "Blueprints", "text": ["From the ground come plans for weapons nobody makes anymore: Ammit's staff, archangel's wings, the bloody anchor."]},
            "shredder": {"title": "Shredder", "text": ["Takes a blueprint apart and teaches you by it. The Arkemer one is better."]},
            "totems": {"title": "Ceramic Totems", "text": ["Blessings of the gods on a permanent basis."]},
            "jewelry": {"title": "Jewelry Table", "text": ["Ruby, topaz, corundum, amber. Quality — from the magnifying glass, sandpaper and the archery skill. Gloves and rings here too."]},
            "rings": {"title": "Rings", "text": ["Lycanthropy, harpy, crimson tears, Hircine. Into accessory slots."]},
        },
    },
    "et_farming": {
        "title": "Garden, Fishing and Catching", "subtitle": "Pots, machines, nets and bug nets",
        "intro": [],
        "quests": {
            "pot": {"title": "Gardener's Pot", "text": ["Plant on top, soil in the slot, from level five — water and fertilizer. Nether and extraterrestrial pots — for other worlds' flora."]},
            "machines": {"title": "Machines", "text": ["One waters, the other fertilizes. Both without you."]},
            "fishing_nets": {"title": "Fishing Nets", "text": ["The net fishes on its own; the nether one — in lava."]},
            "bugs": {"title": "Bug Net", "text": ["Bugs are bait. Rare bug — rare fish."]},
            "pets": {"title": "Pets", "text": ["Raccoons, gultravs, tarkos, comethorn, the ravrite queen. A raccoon can be petted."]},
        },
    },
    "et_overworld": {
        "title": "The Overworld", "subtitle": "Ores, lunar events and first bosses",
        "intro": ["Eternal Tales doesn't start with portals but with the old world ceasing to be familiar: blue cobalt appears in the rock, a red moon rises at night, and someone is digging a hive under the hill."],
        "quests": {
            "ores": {"title": "New Ores", "text": ["Tin, silver, tungsten, cobalt, ruby, uranium, venetium. Cobalt is the first step past diamond. Uranium warms without protection — and not kindly."]},
            "moons": {"title": "Lunar Events", "text": ["The blood moon angers mobs, the blue floods the world with slimes, the clown one — a circus till dawn. Totems summon, loot is unique, survival not guaranteed."]},
            "bosses_ow": {"title": "Overworld Bosses", "text": ["The Ravrite Queen in a hive underground, the Dreadful Sapling from fertile soil, Grotesterk — the legacy of the Xaxxas, of whom you know nothing yet."]},
            "seasonal": {"title": "Seasonal Bosses", "text": ["Ekatebrina — three tiers and an ice serpent. The Halloween Spirit — in October."]},
            "vivid": {"title": "Vivid", "text": ["The one who burned the village, if Miguel is believed. The mod's first truly hard fight; the oathsword after it serves long."]},
            "interdim": {"title": "Interdimensional Creator", "text": ["The workbench where five rarities and a sorcery level fold into a crystal of another world. The return ticket is the first thing to make on it: it brings you home from anywhere and asks only one level."], "rewards": ["Pass to all the mod's dimensions"]},
        },
    },
    "et_nether_end": {
        "title": "Nether and End", "subtitle": "The Piglin Clocktower and the Ancient Chorus",
        "intro": [],
        "quests": {
            "nether_tower": {"title": "Clocktower", "text": ["A tower with a clock piglins couldn't use and locks whose keys are with the overseers of the Blazing Wastes. Who built it, you'll learn in Amber."]},
            "tsar": {"title": "Tsar of Piglins", "text": ["The one with the Crystal Crown. And his warlock."]},
            "nether_res": {"title": "Hellish Resources", "text": ["Bonespur, nether fish, fire moss — into crystals and alchemy."]},
            "end_quest": {"title": "Ancient Chorus", "text": ["A fruit that cures portal disease — the companion of all who walk between worlds."]},
            "endacea": {"title": "Endacea", "text": ["The End's taxi."]},
        },
    },
    "et_comets": {
        "title": "Comets", "subtitle": "First dimension: floating islands and the Terrible Tree",
        "intro": ["Comets are pink-and-blue forests on rocks that should have fallen long ago. The mod's first dimension and its gentlest: here you can still make a mistake and live.", "The Comets crystal needs sorcery level two and five components: ancienzyte-framed bleedwood, inverted mud, terra crystal, grave dirt and a block of hyacinthum gold."],
        "quests": {
            "crystal": {"title": "Comets Crystal", "text": ["Crystal on the creator, portal from comet interdimensional bricks, click — and the sky turns pink."]},
            "enter": {"title": "First Step", "text": ["First extraterrestrial soil level. Between islands — void, and it doesn't forgive."]},
            "skylite": {"title": "Skylite and Aerolite", "text": ["Skylite from ore, aerolite from chests. Both go into the Purgatorium crystal."]},
            "tree": {"title": "Terrible Tree", "text": ["Fell a comet tree with the Tragedy Axe — and the tree answers. The dimension's first boss; from it drops hellfire for the Purgatorium altar."], "rewards": ["Key to Purgatorium"]},
            "quest_comets": {"title": "Comets Quest", "text": ["A banshee in a ruined house, comet fleas in the crater, and the story of the war in which Volcanech wiped this world off the map."]},
            "ice": {"title": "Icelands", "text": ["Cryothermic ice and what lives in it."]},
            "comethorn": {"title": "Comethorn", "text": ["It can be tamed. A strange friendship."]},
        },
    },
    "et_purgatorium": {
        "title": "Purgatorium", "subtitle": "Darkness, the Rock Blaze and the Fallen Rune",
        "intro": ["This is where they exile. Nobody returns — so the Kingdom of Amber believes, and Heveline, living in a ruined house with a dying brother, doesn't argue.", "The crystal needs sorcery level four: fire moss, skylite, lapsidian, aerolite and hellrock."],
        "quests": {
            "hellrock": {"title": "Hellrock", "text": ["Asteroid stone to the altar, hellfire from the Tree in hand — and the altar gives hellrock. Without it the door down won't open."]},
            "rock_blaze": {"title": "Rock Blaze", "text": ["Altar, fire, boss. From it — the first part of the Fallen Rune."]},
            "crystal_purg": {"title": "Purgatorium Crystal", "text": ["A portal of Purgatorium bricks. It's always dark inside."]},
            "rune": {"title": "Fallen Rune", "text": ["First part — from the Rock Blaze, second — from local mob drops, third — from the Wanderer, who doesn't sell it for money."]},
            "nyetet": {"title": "Nyetet, the Fallen Titan", "text": ["He was a hero once. Rune on the altar — and he comes to remind you. Sunstone shards pour from him."], "rewards": ["Sunstone — the key to the Gardens of Eden"]},
            "quest_purg": {"title": "Purgatorium Quest", "text": ["Five Leviathan Blossoms for a dying brother. And the truth about why Heveline is here."]},
            "lapsidian": {"title": "Lapsidian", "text": ["This world's metal. Crystals and gear."]},
        },
    },
    "et_eden": {
        "title": "Gardens of Eden", "subtitle": "The sunny world of the Sunfurry",
        "intro": ["After Purgatorium the light hurts. Here live the Sunfurry — messiahs, huscarls and warriors — and here they drank the Drink of the Sun until Volcanech came for the king.", "The Eden crystal needs level six: silver, two sunstone nuggets, dragon's breath and monster blindness."],
        "quests": {
            "sunstone": {"title": "Sunstone", "text": ["Shards from Nyetet — into a whole stone. The stone — onto the portal in the End."]},
            "enter_eden": {"title": "Gates of Eden", "text": ["Third soil level. The first world where you're welcome."]},
            "crystal_eden": {"title": "Eden Crystal", "text": []},
            "sunfurry": {"title": "Sunfurry", "text": ["Their armor, weapons, trade. The Drink of the Sun — for messiahs and the outsiders who earned it."]},
            "jaghax": {"title": "Jaghax", "text": ["'Tell me what you want?' he'll ask. Answer with a weapon."]},
            "adam_eve": {"title": "Adam and Eve", "text": ["'Are you really the first?' Hidden bosses of the garden."]},
            "scorched": {"title": "Scorched Lands", "text": ["Where Volcanech reached."]},
            "aragotium": {"title": "Aragotium", "text": ["A mythic metal. Component of the Volcanech crystal."]},
        },
    },
    "et_rayana": {
        "title": "Rayana", "subtitle": "Tropics, vampirism and Pterion",
        "intro": ["Jungles where the night lasts longer than it should. The Aede tribe builds temples, the Daredian tribe hides in the mountains, and between them flies what brought the disease here.", "The crystal needs level eight: darkplasm, soulbone, destroyer's eye, sunhog leather, nether fish."],
        "quests": {
            "crystal_ray": {"title": "Rayana Crystal", "text": []},
            "enter_ray": {"title": "Jungles of Rayana", "text": ["Fourth soil level. Hyacinthum gold underfoot."]},
            "vampirism": {"title": "Vampirism", "text": ["Vampires drop the Bloody Stone. From it and local ores — the Bloody Eye."]},
            "pterion": {"title": "Pterion", "text": ["The eye on the Bloody Cult altar in the Aede temple — find it by stone pillars rising from the ground. Pterion descends himself. 'Flying Terror' in the Aede tongue."], "rewards": ["Rayana freed of the plague"]},
            "volkihar": {"title": "Volkihar", "text": ["The vampire lord's power — in your hands."]},
            "kraken": {"title": "Infected Kraken", "text": ["Big, tentacled, from the Mucunfectio quarantine zone."]},
        },
    },
    "et_karvat": {
        "title": "Lands of Karvat", "subtitle": "Divine forest and deities",
        "intro": ["An ancient place where gods still walk the earth and answer the altars' call. The crystal needs level eight: darkplasm, soulbone, comet crystal, spore edennus and crimson eel."],
        "quests": {
            "crystal_kar": {"title": "Karvat Crystal", "text": []},
            "enter_kar": {"title": "Ancient Dimension", "text": []},
            "gods": {"title": "Gods of Karvat", "text": ["Enicrih — the true king. Haciru — the mage. Hirots — disease. Ikkorh — life and death. Arla — strength. Each its own altar, its own shard of power after the fight."]},
            "karvat_quest": {"title": "Divine Power", "text": ["The stolen god Gulibeg and what's left of him — yours."]},
            "khogachi": {"title": "Khogachi", "text": ["Keeper of the tree."]},
            "quetzal": {"title": "Quetzalcoatl", "text": ["The feathered serpent and his priest."]},
        },
    },
    "et_volcanech": {
        "title": "Volcanech", "subtitle": "Volcanoes, aggression and betrayal",
        "intro": ["The world that started the war. From here came the destruction of Comets and the kidnapping of Eden's king; here too are those against it. The crystal needs level ten: ichor, tapinella, aragotium, beetle chitin, dark ichor."],
        "quests": {
            "crystal_vol": {"title": "Volcanech Crystal", "text": []},
            "enter_vol": {"title": "The Molten World", "text": []},
            "golem": {"title": "Volcanic Golem", "text": ["He's very hot. Not a metaphor."]},
            "sulfur": {"title": "Sulfur Explosives", "text": ["The most destructive thing before the atomic bomb. There's an atomic bomb too."]},
            "vol_quest": {"title": "Defection", "text": ["Not everyone here wants war. The road to Amber begins here."]},
            "arahulum": {"title": "Arahulum", "text": ["All the familiar faces. His eye stays with the winner."]},
            "brimstone": {"title": "Brimstone Agaric", "text": ["A mushroom. A boss. A mushroom boss."]},
        },
    },
    "et_amber": {
        "title": "Kingdom of Amber", "subtitle": "A bright dimension with a dark secret",
        "intro": ["A rich, bright, polite world that exiles the unwanted to Purgatorium and keeps in a labyrinth what isn't spoken of. The crystal needs level thirteen: pharos, illuminati fish, flame sphere, truadamantite, Crystal of Greatness."],
        "quests": {
            "truadamantite": {"title": "Truadamantite", "text": ["True power. Armor and brush — best of their kind."]},
            "greatness": {"title": "Crystal of Greatness", "text": ["And the pharos — a beacon. Both into the Amber crystal."]},
            "crystal_amb": {"title": "Amber Crystal", "text": []},
            "enter_amb": {"title": "Amber Lands", "text": ["Fifth, final soil level."]},
            "maze": {"title": "Amber Labyrinth", "text": ["A royal secret under lock. The key — in the kingdom itself, with those who don't want it found."]},
            "xaxxas": {"title": "Xaxxas XIX", "text": ["Prepare for war. The ruler of Amber — the last boss of normal progression."], "rewards": ["Opens the way to Unahzaal"]},
            "keybekium": {"title": "Daredian", "text": ["The metal forged into weapons for the invasion of Eden."]},
            "smuciel": {"title": "Smuciel", "text": ["God's judgment. Hidden boss."]},
        },
    },
    "et_unahzaal": {
        "title": "Unahzaal", "subtitle": "The multiverse and the end of the road",
        "intro": ["Unahzaal isn't a place. It's what remained when all the mod's worlds were joined into one. Its crystal is assembled from the crystals of Amber, Comets, Eden and Volcanech and needs sorcery level sixteen — more than anything before.", "The main progression ends here. Everything after is for those not ready to stop."],
        "quests": {
            "astral": {"title": "Damaged Astral", "text": ["A crystal component. The restored astral is a reward for what comes after."]},
            "crystal_un": {"title": "Unahzaal Crystal", "text": ["Amber, Comets, Eden, Volcanech and the damaged astral — into one crystal."]},
            "enter_un": {"title": "The Multiverse", "text": []},
            "eye": {"title": "Eye of Unahzaal", "text": []},
            "armor_un": {"title": "Unahzaal Armor", "text": ["Chthonic, orichalcum chthonic, Grand Priest. The ceiling of protection."]},
            "unahzaal": {"title": "Unahzaal", "text": ["Journey's end. In Eternal Darkness the fight is different, and so is the reward — the Calamity Ring."]}, 
            "gifts": {"title": "Gifts of Unahzaal", "text": ["One of five. Choose slowly."]},
            "tetra": {"title": "Tetragrammaton", "text": ["The false god and the last choir."]},
        },
    },
    "et_ultimate": {
        "title": "Ultimate World", "subtitle": "Arkemers, aetherium and the real endgame",
        "intro": ["After the end of the road there's one more world. Its crystal folds from Unahzaal, Rayana, Purgatorium, Karvat and the Ultimate Bricks, and in it live the Arkemers — a civilization whose machines make black holes tame."],
        "quests": {
            "crystal_ult": {"title": "Ultimate World Crystal", "text": []},
            "enter_ult": {"title": "The Ultimate World", "text": []},
            "aetherium": {"title": "Aetherium", "text": ["The Arkemers' energy: armor, tubes, weapons."]},
            "arkemer_tech": {"title": "Arkemer Technology", "text": ["Quarry, shredder, gravicycle, smartphone. The 'Aleph' railgun and the 'Heavenbreaker' — their weapons."]},
            "blackhole": {"title": "A Black Hole in Your Hands", "text": ["Stabilized. Miniature. In your pocket. Armor forged in the ergosphere."]},
            "emblems": {"title": "Emblems", "text": ["Grand, singularity, Arkemer."]},
            "ultimate_items": {"title": "Ultimate Items", "text": ["The Ultimate One, The Ultimate Two, the Gauntlet of the Destinies, the Heart of the Elements, the First Prism, the Order of the Universe. There are no items beyond."], "rewards": ["The absolute ceiling of Eternal Tales"]},
            "hammer": {"title": "Hammer of Eternity", "text": ["The multitool, the divine pickaxe and hoe."]},
            "aftermath": {"title": "Aftermath", "text": ["What happened after. The Flecheresha Stone trial — New Game+."]}, 
        },
    },
    "et_darkness": {
        "title": "Eternal Darkness", "subtitle": "Hard mode and humanity",
        "intro": [],
        "quests": {
            "activate": {"title": "Activation", "text": ["The Totem of Eternity. Everything stronger, everything more dangerous. Reversible."]},
            "humanity": {"title": "Humanity", "text": ["Grows from the wicked, falls from the good. Governs essences and opens two bosses that otherwise don't exist."]},
            "nox_luc": {"title": "Noxifer and Luciden", "text": ["Darkness and light. Only here."]},
            "rings_dark": {"title": "Rings of Darkness", "text": ["Calamity, harpy, crimson tears."]},
            "super": {"title": "Super Duper Darkness", "text": ["The advancement is called 'Suicidal Man'. That's a warning."]},
        },
    },
    "et_gear": {
        "title": "Eternal Tales Gear", "subtitle": "Armors, weapons and artifacts",
        "intro": [],
        "quests": {
            "armors_early": {"title": "Early Armors", "text": ["Charged copper, broken bones, forest ranger, treasure hunter."]},
            "armors_mid": {"title": "Mid Armors", "text": ["Dark mage, warlock, whaler, mucus guts, runic."]},
            "armors_late": {"title": "Late Armors", "text": ["Truadamantite, chthonic, orichalcum, priest, ergosphere, aetherium."]},
            "weapons": {"title": "Weapons", "text": ["Ammit's staff, Khonshu's staff, Mixcohuatl's weapon, the Bloody Anchor, the Cephalopods Slayer, Hoz de Muerte, Archangel's Wings — from blueprints dug from the ground."]},
            "ranged": {"title": "Ranged", "text": ["Atimite's crossbow, Rocket's gun, Bowapril, the Arkemer railgun."]},
            "accessories": {"title": "Accessories", "text": ["Celestial sphere, watching sphere, thinking stone, echo anchor, immunity amulets."]},
            "storage_et": {"title": "Portable Chests", "text": ["A chest that walks with you."]},
            "fun": {"title": "Curiosities", "text": ["Smartphone, fursuits, lava lamps, energy drink, gravicycle. The mod knows how to laugh."]},
        },
    },
}
# награды с русского оригинала для узлов, где они есть
EN["et_unahzaal"]["quests"]["unahzaal"]["rewards"] = ["Eternal Tales main progression completed"]
EN["et_ultimate"]["quests"]["aftermath"]["rewards"] = ["Eternal Tales story fully completed"]
