# -*- coding: utf-8 -*-
EN = {
    "ie_start": {
        "title": "Hammer and Coke", "subtitle": "Where Immersive Engineering begins",
        "intro": ["Immersive Engineering doesn't hide its machines in one block. The coke oven is a three-by-three cube, the blast furnace another, the excavator a structure the size of a house. Everything here takes space, pulls cables and needs you walking around with a hammer.", "It all starts where real industry started: with coke."],
        "quests": {
            "manual": {"title": "Engineer's Manual", "text": ["A book of blueprints. Every multiblock is shown in three dimensions, layer by layer. Without it the blast furnace takes two tries; the excavator — never."]},
            "hammer": {"title": "Engineer's Hammer", "text": ["A hit on a multiblock — and a pile of bricks becomes a machine. The hammer also makes plates from ingots at the crafting table, rotates blocks and takes apart the surplus. Wire cutters remove wires, the screwdriver configures."]},
            "coke_oven": {"title": "Coke Oven", "text": ["Twenty-seven coke bricks in a cube, a hammer blow — and the oven breathes. Coal in, coke out, and creosote drips below — the black oil the whole mod stands on. The first real industry in this pack smells exactly like this."], "rewards": ["Coke and creosote oil"]},
            "treated": {"title": "Treated Wood", "text": ["Planks soaked in creosote don't rot and bear the weight of machines. Pour in a barrel or a tank — and make a lot at once: everyone will ask."]},
            "blast": {"title": "Blast Furnace", "text": ["Another cube, this time blast bricks. Iron and coke in — steel out, slowly, with orange light in the cracks. The preheater speeds it up, the advanced furnace doubles it. Steel is the material of everything you build next."], "rewards": ["Steel — the material of the whole mid and late game"]},
            "workbench": {"title": "Engineer's Workbench", "text": ["Blueprints are this bench's language: components, cartridges, turret parts, electronics. It also upgrades the drill, buzzsaw, revolver and railgun."]},
            "components": {"title": "Components", "text": ["Iron, steel, electronic — the consumable parts of any machine. Electronic ones need copper wire and redstone, advanced ones gold too."]},
            "scaffold": {"title": "Scaffolding and Stairs", "text": ["Scaffolds, railings, catwalks. The pack's industrial look stands on them — literally."]},
        },
    },
    "ie_power": {
        "title": "Power Grid", "subtitle": "Wires, voltages, generators and transformers",
        "intro": ["IE wires shock. Not figuratively: touch an uninsulated live wire and at best you get a scare. There's an honesty in it: a grid that can be built wrong is worth building right."],
        "quests": {
            "wire_lv": {"title": "Low Voltage", "text": ["Copper, 2048 per tick. Connector on the machine, wire from connector to connector with a right-click. Insulated — touchable. Bare — not."]},
            "dynamo": {"title": "Dynamo and Water Wheel", "text": ["The dynamo spins anything: a water wheel in a current, a windmill up high. The wheel needs flowing water its full height, the windmill needs sky."]},
            "windmill_ie": {"title": "Windmill", "text": ["Blades and sails. Higher is stronger, rain is weaker."]},
            "capacitor": {"title": "Capacitors", "text": ["A hundred thousand, a million, four million. Sides set with the screwdriver: in, out, none."]},
            "wire_mv": {"title": "Medium Voltage", "text": ["Electrum, 8192 per tick. Gold and silver in the blast furnace or mixer."]},
            "wire_hv": {"title": "High Voltage", "text": ["Steel, 32768 per tick, across kilometers on poles. A relay is an intermediate post that eats nothing. A power line over the forest is the prettiest thing in IE."]},
            "transformer": {"title": "Transformers", "text": ["LV to MV, MV to HV. Direction — by which side the wire connects."]},
            "safety": {"title": "Safety", "text": ["The Faraday suit against current, earmuffs against the diesel's roar, the breaker switch against everything at once. The voltmeter shows what you did wrong."]},
            "thermo": {"title": "Thermoelectric Generator", "text": ["Ice on one side, lava on the other — and current flows from the difference. Little, but forever."]},
            "lightning": {"title": "Lightning Rod", "text": ["A tower waiting for a storm. One strike — and the capacitors are full for a week."]},
        },
    },
    "ie_machines": {
        "title": "Multiblock Machines", "subtitle": "Crusher, press, arc furnace and excavator",
        "intro": [],
        "quests": {
            "crusher_ie": {"title": "Crusher", "text": ["Five by three by three, toothed rollers, a roar. Doubles ore and grinds anything dropped on top — including mobs that walk badly."], "rewards": ["Industrial ore doubling"]},
            "press": {"title": "Metal Press", "text": ["Molds aren't consumed: plates, rods, gears, wire, casings, packing. Make a mold once — and forever."]},
            "arc": {"title": "Arc Furnace", "text": ["Electrodes descend, metal flares. Steel faster than the blast furnace, scrap back into ingots. Graphite electrodes burn out and need replacing."]},
            "assembler": {"title": "Assembler", "text": ["Three crafting recipes at once from a shared buffer. The auto workbench does the same from a blueprint."]},
            "sample": {"title": "Ore Survey", "text": ["Under every chunk lies a vein. Survey tools sample by eye, the drill precisely. The core sample shows what's there and what's left."]},
            "excavator": {"title": "Excavator", "text": ["A house-sized bucket wheel turns slowly over the vein, and ore pours onto the conveyor. The vein thins but never ends. It's the machine everything else is built for."], "rewards": ["Endless ore extraction"]},
            "storage": {"title": "Storages", "text": ["A silo — a mountain of one item. A tank — a lake of one fluid."]},
            "conveyor": {"title": "Conveyors", "text": ["Plain, dropper, extract, vertical, splitter, covered. The sorter divides the flow, the batcher counts."]},
        },
    },
    "ie_chemistry": {
        "title": "Chemistry and Fuel", "subtitle": "Plant oil, ethanol, biodiesel and polymers",
        "intro": [],
        "quests": {
            "squeezer": {"title": "Squeezer", "text": ["Seeds to oil, plants to juice, pulp to fuel."]},
            "fermenter": {"title": "Fermenter", "text": ["Anything that grows ferments to ethanol. Sugar cane best of all."]},
            "refinery_ie": {"title": "Refinery", "text": ["Ethanol with oil — biodiesel. High-power is meaner."]},
            "diesel": {"title": "Diesel Generator", "text": ["The mod's strongest generator. Roars so loud you need earmuffs, eats fuel, and doesn't ask if you're ready for that much energy."], "rewards": ["IE's main late-game power source"]},
            "mixer": {"title": "Industrial Mixer", "text": ["Concrete, potions by the bucket, solutions for processing."]},
            "bottling": {"title": "Bottling Machine", "text": ["Bottles, buckets, canisters — on a conveyor, no hands."]},
            "duroplast": {"title": "Duroplast", "text": ["A polymer from chemical waste. Advanced parts and armor."]},
            "cloche": {"title": "Garden Cloche", "text": ["A glass bell under which anything grows: seed, soil, water, power — and harvest without fields. Works with IE hemp and Farmer's Delight crops."], "rewards": ["Automatic farming"]},
        },
    },
    "ie_gear": {
        "title": "Engineer's Gear", "subtitle": "Weapons, tools and armor",
        "intro": [],
        "quests": {
            "drill_ie": {"title": "Drill", "text": ["Three by three per pass, on energy. A steel head lasts. Upgrades at the workbench: waterproof, tank, area."]},
            "buzzsaw": {"title": "Buzzsaw", "text": ["Fells trees. With the right blade — not only trees."]},
            "revolver": {"title": "Revolver", "text": ["Assembled from parts by blueprint. AP, explosive, incendiary, buckshot, wolfpack, potion. Upgrades — electromagnet, cylinder, dual."]},
            "railgun": {"title": "Railgun", "text": ["Rods of any metal on energy. Hold the button — the charge grows."]},
            "chemthrower": {"title": "Chemthrower", "text": ["Creosote burns, acid eats, water douses. Against crowds."]},
            "powerpack": {"title": "Powerpack", "text": ["Powers everything handheld. The charging station stays home."]},
            "skyhook": {"title": "Skyhook", "text": ["Hook a taut cable and fly along it. A cableway between bases — a minute instead of ten."]},
            "steel_armor": {"title": "Steel Armor", "text": ["Between iron and diamond, from what you have tons of."]},
            "turret": {"title": "Turrets", "text": ["The gun turret eats revolver rounds, the chem one fluid. A target list, energy, and the base defends itself."]},
            "misc_ie": {"title": "Odds and Ends", "text": ["Floodlight, electric lantern, chunk loader, maintenance kit."]},
            "shaders": {"title": "Shaders", "text": ["Skins for weapons and machines. From bags and from the defeated."]},
        },
    },
}
