# -*- coding: utf-8 -*-
EN = {
    "trials_early": {
        "title": "Trials: First Days", "subtitle": "Turn in resources — get what speeds the start",
        "intro": ["Trials work differently from the other chapters. Here the book doesn't ask to see an item — it takes it: press 'Turn in', and the items vanish from your inventory in exchange for a reward.", "Rewards are chosen to be worth more than what you gave — but only if you came for them in time.", "Without the mod on the server, items aren't taken and no reward is given: the trial just gets checked off."],
        "quests": {
            "logs": {"title": "Woodcutter", "text": ["Sixty-four logs of any oak. Trees here fall in layers, so a stack gathers faster than it seems."]},
            "cobble": {"title": "Stonecutter", "text": ["Three stacks of cobblestone. It piles up anyway — let it be useful once."]},
            "iron": {"title": "First Iron", "text": ["Thirty-two ingots. In return — what you hate spending yourself: a pickaxe with Mending lasts a long while."], "rewards": ["One and a half ingots per ingot turned in — ore doubling before Create"]},
            "food": {"title": "Pantry", "text": ["Thirty-two steaks or as much roast chicken. The pack's kitchen will make them pointless soon; for now — a good trade."]},
            "leather": {"title": "Tanner", "text": ["Sixteen leather. A backpack needs less, but the upgraded one is made of iron, and your iron's already been taken."]},
            "glass": {"title": "Glassblower", "text": ["Sixty-four glass. Create asks for glass on nearly every casing — here's its payment."]},
        },
    },
    "trials_mid": {
        "title": "Trials: Factory Hum", "subtitle": "Machine output in exchange for machines",
        "intro": ["Once production runs, turning in a stack of product is easy. Rewards here are parts whose cost isn't material but assembly time."],
        "quests": {
            "alloy": {"title": "Andesite River", "text": ["One hundred twenty-eight andesite alloy. A mixer makes that in a couple of minutes — if you already have one."]},
            "sheets": {"title": "Rolled Stock", "text": ["Sixty-four iron sheets and thirty-two copper."]},
            "brass": {"title": "Brass Standard", "text": ["Sixty-four brass ingots. The first serious trade: in return — what the brass age can't begin without."]},
            "precision": {"title": "Precision Work", "text": ["Sixteen precision mechanisms. Made by hand it's long; made by a crafter line, it's a test of the line."]},
            "steel_ie": {"title": "Steelmaker", "text": ["Sixty-four IE steel ingots. The blast furnace manages in an evening."]},
            "coke": {"title": "Coke Chemistry", "text": ["One hundred twenty-eight coke and eight buckets of creosote."], "rewards": ["A second coke oven lasts the whole game"]},
            "osmium": {"title": "Osmium Reserve", "text": ["Sixty-four osmium and thirty-two Mekanism steel."]},
            "circuits": {"title": "Circuitry", "text": ["Eight advanced circuits. In return — four elite ones: a trade that skips a chemistry tier."]},
            "processors": {"title": "Silicon Valley", "text": ["Sixteen improved Refined Storage processors."]},
            "bread": {"title": "Bread Tribute", "text": ["One hundred twenty-eight bread for the colony. The MineColonies baker makes that in a day, and you get what the colony doesn't make."]},
        },
    },
    "trials_late": {
        "title": "Trials: High Technology", "subtitle": "Turning in rare materials at the pack's peak",
        "intro": ["Here what you give is truly costly. Rewards are items that don't exist in the world: speed modules, disks, top-tier circuits."],
        "quests": {
            "sturdy": {"title": "Heavy Industry", "text": ["Sixty-four Create sturdy sheets."]},
            "electrum": {"title": "Conductor", "text": ["Thirty-two electrum and sixty-four electrum wire."]},
            "nethersteel": {"title": "Gunsmith", "text": ["Sixteen nethersteel ingots from Big Cannons."]},
            "duroplast": {"title": "Polymers", "text": ["Thirty-two duroplast and four buckets of biodiesel."]},
            "atomic": {"title": "Atomic Alloy", "text": ["Sixteen Mekanism atomic alloys."]},
            "polonium": {"title": "Nuclear Cycle", "text": ["Eight polonium and eight plutonium pellets. Proof of a working reactor and waste processing."]},
            "disks": {"title": "Archivist", "text": ["Four 64k disks."], "rewards": ["Eight parts are two new disks; a wireless grid thrown in"]},
            "levitite": {"title": "Lighter Than Air", "text": ["Sixty-four levitite."]},
            "truadamantite": {"title": "True Power", "text": ["Sixteen truadamantite from the Kingdom of Amber."]},
        },
    },
    "trials_bosses": {
        "title": "Trials: Trophies", "subtitle": "Boss victories the book can notice",
        "intro": ["Nothing to turn in here: the book sees the advancement itself and pays. But the rewards here are the biggest."],
        "quests": {
            "dragon": {"title": "Dragonslayer", "text": []}, "wither": {"title": "Wither", "text": []},
            "naga": {"title": "Naga Scales", "text": []}, "lich": {"title": "Lich Dust", "text": []}, "hydra": {"title": "Hydra Head", "text": []},
            "terrible_tree": {"title": "Comet Lumberjack", "text": []}, "nyetet": {"title": "Fallen Titan", "text": []},
            "pterion": {"title": "Winged Terror", "text": []}, "xaxxas": {"title": "Fall of the King", "text": []},
            "unahzaal": {"title": "Journey's End", "text": []}, "raid": {"title": "Colony Defense", "text": []},
        },
    },
    "final_bridges": {
        "title": "Bridges Between Mods", "subtitle": "How three tech lines join into one",
        "intro": ["The pack's branches are self-sufficient, but it truly opens up at the seams. This chapter is a map of the crossings.", "Every quest here needs items from several mods at once: that's the test of whether you've tied production together."],
        "quests": {
            "rot_to_fe": {"title": "Rotation → FE", "text": ["Create Addition's alternator turns rotation into FE. From there energy goes into IE capacitors and Mekanism cubes.", "The reverse is the electric motor: FE becomes rotation again, so Create machines run off a Mekanism reactor."], "rewards": ["A single power system for the whole base"]},
            "ore_chain": {"title": "One Ore Chain", "text": ["Three mods give three processing tiers: Create's millstone and wheels (×2), IE's crusher (×2 with byproducts), Mekanism's chain (×5).", "Optimal: mine with the IE excavator or Mekanism digital miner, process in Mekanism, distribute through Refined Storage."]},
            "fuel_chain": {"title": "Fuel Chain", "text": ["IE's plant oil and ethanol, Create Addition's bioethanol and Mekanism's biofuel all come from the same thing — crops.", "The IE cloche and a Create farm cover the raw material entirely."]},
            "storage_bridge": {"title": "Storage as a Hub", "text": ["Refined Storage's external storage links Create vaults, Mekanism bins, IE silos and MineColonies racks to the network.", "Colony warehouse, factory stock and autocrafting become one inventory."]},
            "autocraft_bridge": {"title": "Autocraft Over Everything", "text": ["The autocrafter works with more than a crafting table: it feeds an IE crusher, Create crafters or a Mekanism enrichment chamber and takes the result.", "One order in the grid runs a chain through three mods."], "rewards": ["Any item in the pack, one click"]},
            "logistics_bridge": {"title": "Two Logistics", "text": ["Create 6 and Refined Storage solve one problem differently: the first hauls physical packages, the second teleports data.", "A sensible compromise: RS at the base, Create packages between outposts and the colony."]},
            "colony_bridge": {"title": "Colony and Tech", "text": ["The colony mechanic can make tech-mod parts once taught. The courier delivers, and the warehouse joins the RS network.", "Result: the colony supplies your factory, and the factory the colony."]},
            "transport_bridge": {"title": "Transport", "text": ["Create trains haul ore from the mine, Aeronautics airships carry cargo over rough terrain, Mekanism teleporters and waystones carry you.", "Create's portable interfaces and Create Addition's energy interface unload transport automatically."]},
            "defense_bridge": {"title": "Defense", "text": ["IE turrets guard the base from mobs, MineColonies guards protect the colony from raids, Big Cannons artillery with radar — from players and air targets.", "All three run on the shared grid."]},
            "energy_bridge2": {"title": "Four Power Systems", "text": [
                "Three new lines joined the old three: Powah, Create: New Age and Ad Astra. They all speak FE, and an Immersive Engineering wire reaches any of them.",
                "The practical upshot: put the generator where fuel is cheap and the machines where it suits you. Distance is a cable problem."]},
            "resource_bridge": {"title": "Ore That Grows", "text": [
                "Mystical Agriculture closes mining for good: every metal in the pack, Mekanism osmium and Powah uraninite included, grows in a field.",
                "Industrial Foregoing's laser drill does the same from bedrock, and Mekanism's digital miner from the ground. Three ways not to swing a pickaxe."]},
            "magic_tech_bridge": {"title": "Magic and Tech", "text": [
                "Botania turns iron into manasteel, Ars Nouveau automates drop collection with critters, Apotheosis hangs affixes on Mekanism tools.",
                "None of these mods knows about the others — but you do, and that's your edge."]},
            "adventure_bridge": {"title": "Adventure and Tech", "text": ["Tech gear makes the adventure mods much easier: MekaSuit takes Cataclysm boss hits, the IE drill digs the Twilight Forest, the Ad Astra jet suit replaces Aether wings.", "And the reverse: Eternal Tales and Aether artifacts boost survival on dangerous production floors."]},
        },
    },
    "final_goals": {
        "title": "Final Goals", "subtitle": "How the pack ends",
        "intro": ["This pack has no single ending. It has ten, and none is mandatory. Below are the peaks of each branch. Reach them all — and you've seen everything here, and realized you've long been building your own game."],
        "quests": {
            "goal_create": {"title": "Peak of Create", "text": ["A fully automated factory on gauges, a railway between sites, and a flying base on Create Aeronautics."]},
            "goal_ie": {"title": "Peak of Immersive Engineering", "text": ["An excavator on a surveyed vein, an arc furnace, diesel generators on home-made biodiesel and the full engineer's toolkit."]},
            "goal_mek": {"title": "Peak of Mekanism", "text": ["Fusion reactor, steam turbine, SPS with antimatter and a fully built MekaSuit."]},
            "goal_storage": {"title": "Peak of Storage", "text": ["A network with 64k disks, wireless access and autocrafting of any depth — or a full set of Mekanism QIO drives."]},
            "goal_colony": {"title": "Peak of the Colony", "text": ["A level-five colony with every building, the full research tree and a garrison that repels any raid."]},
            "goal_adventure": {"title": "Peak of Adventure", "text": ["All three Aether dungeons, the full Twilight Forest boss chain and the Lamp of Cinders in hand."]},
            "goal_eternal": {"title": "Peak of Eternal Tales", "text": ["All nine dimensions, victory over Unahzaal, the Ultimate World and the Arkemers' ultimate items."]},
            "goal_space": {"title": "Peak of Space", "text": ["A tier four rocket, a jet suit and a base on Glacio with an oxygen distributor. Another star system, properly settled."]},
            "goal_magic": {"title": "Peak of Magic", "text": ["The Gaia Guardian in his second form, the Dice of Fate and at least one relic. Flower magic taken to its end."]},
            "goal_hunt": {"title": "Peak of the Hunt", "text": ["All ten Cataclysm bosses and a full set of Ignitium armor. A trophy hall with no empty spots."]},
            "goal_all": {"title": "All at Once", "text": ["Ten peaks climbed. The pack leads you nowhere further — from here you lead it.", "A good next goal: build what no mod foresaw but their parts allow."], "rewards": ["Pack fully completed"]},
        },
    },
    "end_monuments": {
        "title": "Monuments", "subtitle": "Builds that justify the whole factory",
        "intro": ["The pack's finale isn't a fight or an item. The finale is what stays standing when you log out. Every quest here demands product in amounts that can't be made by hand at all. Only a factory. Only automation.", "Turn in — receive. And receive what speeds the next monument."],
        "quests": {
            "spire": {"title": "Spire", "text": ["One thousand twenty-four Create metal girders. A tower of them is visible from the next chunk, if Distant Horizons doesn't lie."]},
            "bridge": {"title": "Bridge Across the World", "text": ["Two thousand forty-eight tracks. A line from base to colony, colony to mine, mine to the airship pier. A train circling for half an hour."]},
            "vault_city": {"title": "Million-Slot Vault", "text": ["Sixteen 64k disks. A million slots. A network enough for everything you'll ever mine."]},
            "matrix": {"title": "Matrix", "text": ["Fifty-four casings and eight ultimate induction cells. A battery that outlives a fusion reactor."]},
            "shipyard": {"title": "Shipyard", "text": ["Two hundred fifty-six pearlescent levitite and sixty-four smart propellers. That's what it takes to lift something the size of a colony."]},
            "fortress": {"title": "Bastion", "text": ["Eight nethersteel screw breeches and one hundred twenty-eight HE shells. A fortress that isn't taken."]},
            "cathedral": {"title": "Cathedral", "text": ["Two thousand blocks through the architect's cutter — any, but not vanilla. Domum Ornamentum makes them from anything; only patience matters. The book accepts timber frame: one thousand twenty-four panels."]},
            "eternal_town": {"title": "Eternal Town Rebuilt", "text": ["Five hundred twelve Ultimate Bricks. Rebuild Eternal Town from a material only the Arkemers make."]},
        },
    },
    "end_marathon": {
        "title": "Marathon", "subtitle": "Numbers you can't catch without an autocraft chain",
        "intro": ["No bosses and no builds here — only volume. Each quest is turned in with one press, but gathered only by a network that makes things itself. It's an autocraft test disguised as greed."],
        "quests": {
            "mech1024": {"title": "A Thousand Mechanisms", "text": ["One thousand twenty-four precision mechanisms. One crafter line gives one every few seconds; count how many lines you need."]},
            "steel4096": {"title": "Four Thousand Steel", "text": ["Four thousand ninety-six IE steel ingots. An arc furnace on a diesel grid — the only realistic path."]},
            "circuits256": {"title": "Two Hundred Fifty-Six Ultimates", "text": ["Atomic alloy in industrial amounts. Without fivefold ore and twenty-deep autocrafting it's impossible."]},
            "antimatter64": {"title": "Antimatter", "text": ["Sixty-four antimatter pellets. An SPS running a week on a fusion reactor. This isn't a game anymore, it's physics."]},
            "processors1024": {"title": "A Thousand Processors", "text": ["One thousand twenty-four advanced processors. A network that makes itself."]},
            "crystals9": {"title": "Nine Worlds in a Pocket", "text": ["One crystal of every Eternal Tales dimension — all nine, turned in at once. It means you can return anywhere at any moment. Which means you can give them up."]},
        },
    },
    "end_apotheosis": {
        "title": "Apotheosis", "subtitle": "The book's last quests",
        "intro": ["Three things hardest to do, and one that can't be done without doing everything else."],
        "quests": {
            "darkness_unahzaal": {"title": "Darkness Defeated", "text": ["Unahzaal in Eternal Darkness. The Calamity Ring is the proof."]},
            "arkemer": {"title": "Arkemer Legacy", "text": ["A stabilized black hole, the Order of the Universe, the First Prism, both Ultimate items. Everything left by a civilization that could do more than us."]},
            "seven": {"title": "Seven Peaks", "text": ["Factory gauge, excavator, antimatter, million-slot vault, level-five colony, Lamp of Cinders, Ultimate World. Not to turn in — to show."]},
            "codex": {"title": "Codex Closed", "text": ["The three nodes above — and one nether star in hand. The book has nothing more to tell you. Thank you for reading to the end.", "Beyond — what no mod foresaw and what's possible from their parts. That's your book now."], "rewards": ["Pack fully completed"]},
        },
    },
    "story_forge": {
        "title": "The Engineer's Road", "subtitle": "From the first alloy to a train that hauls ore by itself",
        "intro": ["There's an easy way to know what your factory is worth: stop walking up to it. This line leads from a hand on a crank to a train that leaves for the mine on schedule and returns with ore while you sleep.", "The forks are real: you can go through wind or water, through millstone or wheels. They meet on one thing — the train."],
        "quests": {
            "hand": {"title": "Hand on the Crank", "text": ["The first turn of a shaft is always yours. A press on a hand crank, ten iron sheets, blisters. Remember the feeling: water will replace it soon."]},
            "wind": {"title": "The Way of Wind", "text": ["A bearing, sixty-four sail frames, a high point. A windmill needs nothing but sky, and for that it's forgiven its slowness."]},
            "water": {"title": "The Way of Water", "text": ["Two large wheels in a closed channel. Quieter than a windmill, more reliable, weather-proof. Classic."]},
            "source": {"title": "Source Found", "text": ["Either path leads here: to a stressometer whose needle, for the first time, isn't in the red. Now you can place machines, not toys."]},
            "source_w": {"title": "Source Found", "text": ["A twin of the node above: the fork rejoins. The book counts whichever path you took."]},
            "mill": {"title": "Millstone or Wheels", "text": ["The fast path — a millstone, cheap and slow. It gives the first hundred crushed pieces and shows that ore can double."]},
            "wheels": {"title": "Millstone or Wheels", "text": ["The long path — brass, crushing wheels, a stream. Pricier going in, five times faster coming out. Turn in one hundred twenty-eight crushed iron from the wheels — and the book believes the line works."]},
            "smelt": {"title": "Smelting Row", "text": ["A fan over lava, a belt under it, a chest at the end. Crushed goes in, ingots come out. The first place on the base where nothing needs hands."]},
            "boiler": {"title": "Boiler to Eighteen", "text": ["Tank, four burners, four engines. Boiler level grows with volume and heat; your first will be level two, and that's enough to stop the windmill for good."]},
            "precision": {"title": "Precision Line", "text": ["Five crafters in a ring, deployers with gold sheet, rods and cogs, a belt around. Turn in eight mechanisms assembled without hands."]},
            "rails": {"title": "First Line", "text": ["Sixty-four tracks from base to mine. Not straight — Create does lovely curves, and the first tracks take longer than needed simply because it's nice to watch."]},
            "train": {"title": "A Train That Doesn't Wait", "text": ["A locomotive with a boiler, a wagon with portable interfaces, a schedule: 'to the mine, wait for full, home, wait for empty, repeat'. A conductor in a cap. Step back and watch it leave."], "rewards": ["The first achievement that moves by itself"]},
        },
    },
    "story_current": {
        "title": "Current", "subtitle": "Three factories — one power grid",
        "intro": ["The pack's three technologies live apart for a long time: Create spins shafts, IE strings wires, Mekanism keeps quiet and enriches. This line is about making them talk to each other, and it ends with a reactor that feeds everything."],
        "quests": {
            "coke": {"title": "Smoke Over the Coke Oven", "text": ["IE's first step is always coke. Turn in sixty-four — the book needs to know the oven breathes, not just stands."]},
            "steel": {"title": "Steel of Two Houses", "text": ["The pack has two steels, and they aren't interchangeable. IE's blast furnace and Mekanism's infuser — build both. This node is the first place two mods stand on one pad."]},
            "dynamo": {"title": "First Current", "text": ["An IE water wheel on a dynamo, copper wire to a capacitor. Little, but already energy — the kind Mekanism understands."]},
            "alternator": {"title": "Shaft into Wire", "text": ["A Create Addition alternator on a steam boiler. Rotation goes into wire, wire into an IE capacitor. The first handshake between Create and IE."]},
            "grid": {"title": "One Grid", "text": ["A transformer raises voltage, steel wire carries it across the yard, a Mekanism energy cube receives. One meter for three mods."]},
            "ore5": {"title": "Fivefold Ore", "text": ["The grid exists — now there's something to feed. Mekanism's full chain: dissolution, washing, crystallization. Turn in sixty-four iron crystals — proof the setup lives."]},
            "diesel": {"title": "Diesel", "text": ["The cloche grows, squeezer and fermenter process, the refinery mixes, the generator roars. Turn in sixteen buckets of biodiesel — the grid must survive the night."]},
            "fission": {"title": "Heart of the Base", "text": ["Fission reactor, boiler, turbine, matrix. Three mods, one wire, a gigawatt. Turn in four fuel assemblies — spares, not the ones in the reactor."], "rewards": ["Energy you stop counting"]},
        },
    },
    "story_expedition": {
        "title": "Expedition", "subtitle": "Through every world, in the order they open",
        "intro": ["The pack leads you through foreign worlds not at random but in order: sky first, then twilight, then comets — and onward along the spiral Volcanech's war laid out. This line is a route, and it has only one destination."],
        "quests": {
            "kit": {"title": "Kit", "text": ["A waystone at home, two return scrolls, a charm of life from the Twilight Forest — no, not yet. For now: stone, scrolls, a sleeping bag and a promise to yourself not to forget coordinates."]},
            "sky": {"title": "Sky", "text": ["Aether first: gentler than the rest, and it teaches the main thing — watch your feet. Bronze dungeon, key, medal."]},
            "dusk": {"title": "Twilight", "text": ["Twilight Forest second: strict but fair. Naga in the courtyard, Lich in the tower. After them the forest opens."]},
            "comets": {"title": "Comets", "text": ["Sorcery level two, five components, a crystal. A pink sky and a tree that answers an axe."]},
            "purg": {"title": "Purgatorium", "text": ["Hellrock from the altar, the Rock Blaze, three rune parts, Nyetet. It's dark here, and the exiles tell you why."]},
            "eden": {"title": "Eden", "text": ["The sunstone opens the portal in the End. The Sunfurry pour the Drink of the Sun if you've earned it."]},
            "rayana": {"title": "Rayana", "text": ["Jungles and vampires. The Bloody Eye on the Aede altar — Pterion."]},
            "karvat": {"title": "Karvat", "text": ["Gods on altars. At least three of five."]},
            "volcanech": {"title": "Volcanech", "text": ["The aggressor world. Golem, sulfur TNT, deserters, Arahulum."]},
            "amber": {"title": "Amber", "text": ["Sorcery level thirteen. Labyrinth, secret, Xaxxas."]},
            "unahzaal": {"title": "Journey's End", "text": ["All crystals into one. Level sixteen. The multiverse and the one who holds it."], "rewards": ["The expedition is over. Another game begins"]},
        },
    },
    "story_colony": {
        "title": "A City That Grows Itself", "subtitle": "The colony from four citizens to a technopolis",
        "intro": ["MineColonies is the only mod in the pack where progress happens while you're away. This line is about how a supply chest grows into a city that supplies your factory, and the factory supplies it."],
        "quests": {
            "found": {"title": "Four", "text": ["Chest, town hall, builder, first house. Four citizens who have nothing yet but you."]},
            "supply": {"title": "Warehouse and Bread", "text": ["Warehouse, courier, farmer, cook. Turn in sixty-four bread — the colony must eat while you build."]},
            "wood": {"title": "Forest and Stone", "text": ["Lumberjack, sawmill, miner, stonemason. This is where the colony gets everything it builds."]},
            "guard": {"title": "First Night Under Guard", "text": ["Two towers and a rally banner. The raid comes sooner than you think."]},
            "population": {"title": "Twenty-Five", "text": ["Tavern, more houses, hospital. Twenty-five citizens is a town with character."]},
            "science": {"title": "University", "text": ["Library, school, university. First research started."]},
            "industry": {"title": "Smithy and Mechanic", "text": ["Smeltery, blacksmith, mechanic. The mechanic can make Create and IE parts — teach him, and the colony starts supplying the factory."]},
            "network": {"title": "Warehouse on the Network", "text": ["Refined Storage external storage on the warehouse racks. Now everything the colony brings shows in the grid — and vice versa."]},
            "garrison": {"title": "Garrison", "text": ["Barracks with four towers, academy, archery. Eight guards by advancement — and the night no longer frightens."]},
            "fifty": {"title": "Fifty", "text": ["Fifty citizens, a level-five town hall in the plans, a mystical site for happiness. A city."]},
            "technopolis": {"title": "Technopolis", "text": ["Level-five town hall. A colony that feeds the factory and defends itself. Turn in eight Mekanism ultimate circuits made by the mechanic's hands or yours — no matter; what matters is both sides reached the end."]},
        },
    },
    "story_sky": {
        "title": "Sky and Powder", "subtitle": "Air fleet, artillery and radar — one defense",
        "intro": ["An airship without a gun is a stroll. A gun without radar is fireworks. This line gathers three mods into one system: flying platform, targeting, salvo."],
        "quests": {
            "lift": {"title": "Ascent", "text": ["Assembler, levitite, envelope, burner. The first airship is a wooden box that flies anyway."]},
            "cast": {"title": "Casting", "text": ["Cast iron, sand, molds, drill. Turn in four bored cast-iron barrels — with them you can already shoot."]},
            "eyes": {"title": "Eyes", "text": ["Radar, plates, data link, monitor. The first time you see the target before it sees you."]},
            "mount": {"title": "Aiming", "text": ["Mount, yaw and pitch controllers, fire controller. The radar speaks — the gun turns. No hand at all."]},
            "flak": {"title": "Anti-Air", "text": ["An autocannon with a steel barrel and flak rounds. Turn in sixty-four — against air targets you don't bring fewer."]},
            "missile": {"title": "Missile", "text": ["Motor, fins, computer, proximity fuze, launcher. A missile is a physics object, and it flies for real."]},
            "fleet": {"title": "Flagship", "text": ["An airship with a gyroscope, portable engine, navigation table, an autocannon on deck and a launcher under the gondola. A transponder — so your own AA doesn't shoot it down. Turn in four gyroscopic mechanisms: a fleet needs stability."], "rewards": ["The sky is yours"]},
        },
    },
    "fd_kitchen": {
        "title": "Kitchen", "subtitle": "Farmer's Delight: knives, board, pot and skillet",
        "intro": ["Farmer's Delight turns food into a system. Finished dishes give the Nourishment effect — hunger stops draining for a while, noticeably handier than vanilla steaks."],
        "quests": {
            "knife": {"title": "Knife", "text": ["The knife slices ingredients on the board and serves as a light weapon. Flint, iron, gold, diamond, netherite."]},
            "board": {"title": "Cutting Board", "text": ["The board takes things apart: a knife gives cuts of meat, an axe planks, a pickaxe rubble.", "It's also the cheapest way to skin and butcher a carcass."]},
            "pot": {"title": "Cooking Pot", "text": ["The pot cooks soups and stews over a campfire. A recipe — up to six ingredients plus a container (bowl, bottle).", "Put several pots on one long campfire — you get a kitchen."]},
            "skillet": {"title": "Skillet", "text": ["The skillet fries faster than a furnace and works right in your hands over a fire source. Also a decent weapon that sets things ablaze."]},
            "stove": {"title": "Stove", "text": ["The stove fries up to six items at once and shows them on its surface."]},
            "crops": {"title": "New Crops", "text": ["Tomatoes, cabbage, onions, rice. Wild versions grow in matching biomes — that's where to start.", "Rice goes in shallows, tomatoes need a trellis."]},
            "soil": {"title": "Rich Soil", "text": ["Organic compost is made in the composter from organics, straw from wheat. Rich soil speeds growth and needs no watering."]},
            "feast": {"title": "Feast", "text": ["Feast dishes go on a table and feed several players: roast chicken, pie, honey-glazed ham, baked cod."], "rewards": ["The best food in the pack"]},
            "storage_fd": {"title": "Food Storage", "text": ["Cabinets, baskets and crates for the harvest. A crate packs nine into one block."]},
            "rope": {"title": "Rope and Hanging", "text": ["Rope lets you hang items, and 'bundles' dry the harvest."]},
        },
    },
    "life_furniture": {
        "title": "Furniture and Comfort", "subtitle": "Handcrafted, Refurbished Furniture, Furnicraft and decor",
        "intro": ["The pack has three independent furniture mods plus the decorative blocks of Create, Domum Ornamentum and Eternal Tales. Together they cover any interior."],
        "quests": {
            "handcrafted": {"title": "Handcrafted", "text": ["Tables, chairs, benches, cupboards, nightstands and shelves for every wood, plus crockery, cushions, sheets, mob trophies and wall decor.", "Trims and corner pieces give tidy wall joints."]},
            "refurbished": {"title": "Refurbished Furniture", "text": ["Modern furniture: kitchens with sinks and cabinets, bathrooms, sofas, blinds, ceiling fans, mailboxes, a TV and a working computer.", "Many items are functional: the sink draws water, the fridge stores food, the toaster toasts bread."]},
            "furnicraft": {"title": "Furnicraft", "text": ["Furnicraft in this pack is a datapack (ketket_furnitures). Furniture is assembled at the carpenter's bench from wood, iron, wool and lanterns.", "Recipes are fully described inside the datapack and visible in JEI."], "tasks": ["Build any Furnicraft furniture"]},
            "domum": {"title": "Domum Ornamentum", "text": ["The architect's cutter makes brick, tile, timber frame, panels, lights, carpets and doors from any materials.", "Formally a MineColonies library, but its blocks are useful in any build."]},
            "create_deco2": {"title": "Create Decor", "text": ["Copper shingles and tiles in every oxidation stage, framed glass, girders, ladders, table cloths, postboxes and nixie tubes.", "Copycat blocks take the look of any other block."]},
            "et_deco": {"title": "Eternal Tales Decor", "text": ["The mod adds hundreds of blocks from every dimension: amber bricks, comet wood, eden stone, lava lamps, vases, paintings and records.", "The museum and showcases let you display trophies."]},
            "comforts2": {"title": "Hammocks and Bags", "text": ["The hammock hangs from a rope-and-nail and skips the day. The sleeping bag skips the night without moving your spawn."]},
            "macaw": {"title": "The Macaw's Series", "text": ["Seven mods by one author cover what vanilla lacks entirely: roofs at real angles, doors and gates of every kind, windows with shutters, stairs and railings, bridges, lamps and holiday decor.", "Everything crafts from ordinary materials and fits any style, from rustic to industrial."]},
        },
    },
    "more_vanilla": {
        "title": "Old Roads", "subtitle": "Vanilla progression the pack won't let you forget",
        "intro": ["Under ninety mods lies the same game: diamonds deep down, an enchanting table, netherite, a beacon. Mods don't cancel it — they make it faster and prettier."],
        "quests": {
            "diamonds": {"title": "Diamonds", "text": ["At minus fifty-eight. A pickaxe, then everything else."]},
            "enchant": {"title": "Enchanting Table", "text": ["Fifteen shelves, lapis, luck. Eternal Tales' astral enchanter will later do what this table can't."]},
            "villagers": {"title": "Trade", "text": ["Emeralds and villagers in Easy Villagers blocks. A librarian with Mending is goal number one."]},
            "netherite": {"title": "Netherite", "text": ["Four scraps, four gold. One thing for yourself, the rest into the diving set and cannons."]},
            "beacon": {"title": "Beacon", "text": ["A nether star and a pyramid. Speed across the whole base — a small MekaSuit module many hours before MekaSuit."]},
            "trims": {"title": "Armor Trims", "text": ["Trim templates — vanilla and modded: Eternal Tales adds sixty materials and thirty patterns."], "tasks": ["", "Apply a trim to any armor"]},
            "elytra2": {"title": "Elytra and Rockets", "text": ["Sixty-four rockets. Until flight modules are far off, this is the sky."]},
        },
    },
    "more_explore": {
        "title": "Atlas", "subtitle": "Biomes of Terralith and other worlds",
        "intro": ["Terralith reshaped the world, and most of it you'll never see unless you go on purpose. This atlas is a list of places worth going. The book marks a biome as soon as you stand in it."],
        "quests": {
            "sakura": {"title": "Sakura Grove", "text": ["Terralith's pink forest. Build a house here — you'll want to anyway."]},
            "lavender": {"title": "Lavender Valley", "text": ["Terralith's lavender fields — valley and forest side by side. Find both."]},
            "amethyst": {"title": "Amethyst Canyon", "text": ["Purple stone and crystals growing from the walls."]},
            "glacial": {"title": "Glacial Chasm", "text": ["Terralith's coldest and deepest place."]},
            "skylands": {"title": "Skylands", "text": ["Islands in the air, before Aether. Spring, autumn — any."]},
            "volcano": {"title": "Caldera", "text": ["A Terralith volcano with a lake inside."]},
            "mystic": {"title": "Emerald Peaks", "text": ["Terralith's green mountains, where emerald sits outside the veins too."]},
            "ominous": {"title": "Volcanic Crater", "text": ["Another Terralith volcano — with a lava lake instead of water."]},
            "redwood": {"title": "Cloud Forest", "text": ["Fog between the trunks and moss up to your knees."]},
            "wasteland": {"title": "Painted Mountains", "text": ["Striped terracotta slopes in every shade."]},
            "hotsprings": {"title": "Moonlight Grove", "text": ["A night biome glowing with its own light."]},
            "endbop": {"title": "Mirage Isles", "text": ["Mirage islands in the middle of a warm ocean."]},
            "geob": {"title": "Geobstractsite", "text": ["Eternal Tales' radioactive biome in the overworld. Don't linger."]},
            "mucun": {"title": "Mucunfectio", "text": ["Quarantine zone. Crabs."]},
            "amberian": {"title": "Amberian City", "text": ["The capital of the Kingdom of Amber."]},
            "atlas_done": {"title": "Atlas Complete", "text": ["Fifteen places you've stood in. Xaero's map remembers each."]},
        },
    },
    "more_kitchen": {
        "title": "Cookbook", "subtitle": "Farmer's Delight, the MineColonies kitchen and Eternal Tales food",
        "intro": [],
        "quests": {
            "stew": {"title": "Three Soups", "text": ["Beef stew, chicken soup, fish stew. A pot and patience."]},
            "bread": {"title": "Sandwiches", "text": ["Bacon, chicken, egg — between two slices. Road food."]},
            "pies": {"title": "Pies", "text": ["Apple, chocolate, sweet berry. Whole — onto the table."]},
            "colony_food": {"title": "Colony Kitchen", "text": ["MineColonies adds dozens of dishes: pizza, borscht, kimchi, lembas. The cook makes them himself, but so can you."]},
            "et_food": {"title": "Food of Other Worlds", "text": ["Crabsburger, mutatongue chowder, blueberry cookies. Eternal Tales feeds strangely but well."]},
            "feast_hall": {"title": "Feast", "text": ["Honey-glazed ham, roast chicken, stuffed pumpkin — three feasts on one table. Call your friends."]},
        },
    },
    "more_rails": {
        "title": "Depot", "subtitle": "Steam 'n' Rails in all its glory",
        "intro": [],
        "quests": {
            "locomotive": {"title": "Steam Locomotive", "text": ["Smokestack, boiler, smokebox, plating. A locomotive that looks like a locomotive."]},
            "couplers": {"title": "Couplers", "text": ["Four couplers — four wagons. Trains of different length on one track."]},
            "semaphore": {"title": "Semaphores", "text": ["Arms instead of lamps. Work like signals, look like history."]},
            "crossing": {"title": "Crossing", "text": ["Where the road meets the track."]},
            "fuel": {"title": "Diesel", "text": ["A fuel tank and a diesel stack. A train without coal."]},
            "depot": {"title": "Depot", "text": ["Three trains with schedules, a handcar for track inspection, a conductor on each. Turn in four caps — you have a staff."]},
        },
    },
    "more_munitions": {
        "title": "Arsenal", "subtitle": "Munitions, fuzes and battery supply",
        "intro": [],
        "quests": {
            "powder": {"title": "Powder Magazine", "text": ["Sixty-four charges. That's what one good evening uses."]},
            "fuzes": {"title": "Fuzes", "text": ["Impact, inertia, timed, proximity, wired. Eight of each — for any case."]},
            "shells": {"title": "Shell Rack", "text": ["Shrapnel, smoke, fluid. Not everything has to explode."]},
            "belt": {"title": "Belt", "text": ["One hundred twenty-eight cartridges and a container. The autocannon eats fast."]},
            "mg": {"title": "Machine Gun", "text": ["Faster still. Smaller caliber."]},
            "supply": {"title": "Battery Supply", "text": ["The requester orders charges and shells from stock, the frogport delivers, the loader rams. The battery fires as long as there's powder in the warehouse."]},
        },
    },
    "more_et_side": {
        "title": "Side Paths", "subtitle": "What in Eternal Tales doesn't lead to Unahzaal but is worth the time",
        "intro": [],
        "quests": {
            "raccoons": {"title": "Raccoons", "text": ["Every kind. The cookie reward — from them too."]},
            "tarkos": {"title": "Tarkos", "text": ["A prehistoric band."]},
            "chests": {"title": "Four Chests", "text": ["Digging, fishing, growing, sorcery — every skill leaves a chest."]},
            "lamps": {"title": "Light of the Night", "text": ["All the lava lamps. Cozy."]},
            "music": {"title": "Collector", "text": ["All the mod's records. Thirty-eight."]},
            "blue_moon": {"title": "Blue Moon", "text": ["Survive the night of slimes."]},
            "clown": {"title": "Circus", "text": ["The clown moon. Not funny."]},
            "crabs": {"title": "Crabsapocalypse", "text": ["They're coming."]},
            "arky": {"title": "Arky", "text": ["A pretty raccoon and his suit."]},
            "gravicycle": {"title": "Gravicycle", "text": ["Build it, push it to the limit, don't crash."]},
            "bomb": {"title": "Royal Boom", "text": ["Eternal Tales' atomic bomb. Away from the base. Further."]},
            "darwin": {"title": "Darwin Award", "text": ["Die all three stupid ways. The book doesn't judge."]},
        },
    },
    "more_home": {
        "title": "Home", "subtitle": "Comfort as a discipline of its own",
        "intro": [],
        "quests": {
            "bed": {"title": "Bedroom", "text": ["Bed, nightstand, lamp, rug. Handcrafted and Refurbished — your pick."]},
            "kitchen": {"title": "Kitchen", "text": ["Sink, cabinets, fridge, toaster. All working."]}, 
            "workshop": {"title": "Workshop", "text": ["The architect's cutter, the Furnicraft carpenter's bench, Create's schematic table. The place a home is made."]},
            "garden": {"title": "Garden", "text": ["Beds on rich soil, an Eternal Tales gardener's pot, an IE cloche. Three schools of farming in one yard."]},
            "hall": {"title": "Hall", "text": ["Boss trophies on the walls, a Twilight Forest pedestal, an Eternal Tales museum showcase. A home with something to tell."]},
        },
    },
}
EN["more_home"]["quests"]["kitchen"]["tasks"] = ["Assemble a kitchen from Refurbished Furniture"]
