# -*- coding: utf-8 -*-
EN = {
    "rs_network": {
        "title": "Refined Storage: Network", "subtitle": "Controller, cables, disks and grids",
        "intro": ["Refined Storage moves a warehouse from space into data. Chests, racks, Create vaults — all become lines in one list, and search replaces running between boxes.", "The network's real value shows later, when it starts doing things itself. But it all begins with a controller and one thousand-item disk."],
        "quests": {
            "silicon": {"title": "Silicon and Processors", "text": ["Quartz to silicon, silicon with iron or gold to a blank, blank into the furnace. Three tiers of processors — the consumable of the whole network."]},
            "quartz_iron": {"title": "Quartz Enriched Iron", "text": ["Quartz and iron. Cables, housings, everything."]},
            "controller": {"title": "Controller", "text": ["The heart. Takes energy, hands it to all who are connected. One network — one controller; more devices, more it eats."], "rewards": ["A working storage network"]},
            "cable": {"title": "Cables and Relay", "text": ["The cable connects. The relay switches a segment on and off by condition."]},
            "drive": {"title": "Disk Drive and Disks", "text": ["Eight disks in one block. One, four, sixteen, sixty-four thousand items. The housing lets you take a disk apart again."]},
            "grid": {"title": "Grid", "text": ["A window into the network: search, sort, move. The crafting grid adds a table, the pattern grid writes recipes. Portable — in your pocket on a battery."], "rewards": ["One access point to the whole warehouse"]},
            "blocks_storage": {"title": "Storage Blocks", "text": ["A disk that became a block. No drive needed."]},
            "external": {"title": "External Storage", "text": ["Chest, barrel, Create vault, tank — all become part of the network. The disk interface pours between disks."]},
            "io": {"title": "Import and Export", "text": ["Importer takes, exporter gives by filter, interface goes both ways. Upgrades: speed, stack, regulator, silk, fortune."]},
            "constructor": {"title": "Constructor and Destructor", "text": ["The constructor places blocks from the network into the world, the destructor breaks and stores. A wall that builds itself."]},
            "monitor": {"title": "Monitor and Detector", "text": ["A number on a block. A signal at a threshold."]},
            "wireless": {"title": "Wireless Access", "text": ["The transmitter gives coverage, the grid opens the network from anywhere. Network transmitter and receiver link segments — even across dimensions."]},
            "security": {"title": "Security", "text": ["Who may do what."]},
        },
    },
    "rs_autocraft": {
        "title": "Refined Storage: Autocrafting", "subtitle": "Patterns, autocrafters and production chains",
        "intro": ["Autocrafting is the moment the network stops being a warehouse and becomes a conversation partner. You ask for 'a hundred precision mechanisms', it computes a tree of forty recipes, finds what's missing, and makes it. You wait."],
        "quests": {
            "pattern_grid": {"title": "Pattern Grid", "text": ["A recipe is written onto a pattern. Crafting table, furnace, crusher, any machine with a filter — all can be described."]},
            "autocrafter": {"title": "Autocrafter", "text": ["Stores patterns, executes. For machines — hands components to a neighbor and waits for the result."], "rewards": ["Automatic production on demand"]},
            "manager": {"title": "Pattern Manager", "text": ["All patterns in one list; duplicates and conflicts visible at once."]},
            "monitor_craft": {"title": "Autocrafting Monitor", "text": ["What's being made, what's waiting, what's stuck."]},
            "upgrade_craft": {"title": "Crafting on Demand", "text": ["In an exporter or interface: no item — the network makes it. That's how you keep a stock you don't think about."]},
            "wireless_craft": {"title": "Wireless Monitor", "text": ["The same monitor, in your pocket."]},
            "jei_rs": {"title": "JEI Integration", "text": ["From a JEI recipe straight to an order in the network. The grid highlights what's missing."], "tasks": ["Order a craft from JEI through the grid"]},
            "big_project": {"title": "The Big Chain", "text": ["Order eight advanced processors with one click. Silicon, gold, redstone, blanks, furnace — if the network assembled this itself, it's configured."], "rewards": ["Fully automated production"]},
        },
    },
    "storage_local": {
        "title": "Local Storage", "subtitle": "Backpacks, chests and everything that needs no network",
        "intro": [],
        "quests": {
            "backpack_tiers": {"title": "Backpack Tiers", "text": ["Copper, iron, gold, diamond, netherite. Each tier — more slots and more upgrades, and nothing lost along the way."]},
            "backpack_auto": {"title": "Automation in a Backpack", "text": ["Smelting, blasting, smoking on the move. A crafting table and anvil inside. A brewing stand. Compacting ore into blocks. The backpack becomes a small base."]},
            "backpack_filter": {"title": "Filters and Pumps", "text": ["The filter sifts junk, void destroys it, deposit dumps into a chest, refill keeps the hotbar full. Pump — fluids, battery — energy."]},
            "everlasting": {"title": "Indestructible Backpack", "text": ["Won't burn and won't vanish. Insurance against lava."]},
            "vault_create": {"title": "Create Vault", "text": ["Cheap, big, and joins the network via external storage. A raw-material warehouse before a real network."]},
            "bins": {"title": "Mekanism Bins", "text": ["One item, but very many. Cobblestone, wood, ore."]},
            "rack": {"title": "Colony Racks", "text": ["The colony warehouse — also external storage for the network."]},
        },
    },
    "mc_found": {
        "title": "Founding a Colony", "subtitle": "Town hall, builder and first citizens",
        "intro": ["MineColonies is a game where you don't build. You decide what to build, find materials and wait for someone else to lay stone on stone. At first it's annoying. Then it becomes clear the colony grows while you're off in the Twilight Forest, and that's the best kind of automation there is."],
        "quests": {
            "supply": {"title": "Supply Chest", "text": ["Chest on water, camp on land. Unfolds into a starting pad with town hall, builder and stock. Placed once — pick a spot you'd live a hundred hours at."]},
            "townhall": {"title": "Town Hall", "text": ["The town hall declares borders and opens the citizen list, statistics, permissions. Its level is the population cap."], "rewards": ["Your own colony"]},
            "buildtool": {"title": "Build Tool", "text": ["A ghost of a building goes on the ground, rotates, confirms — and the builder gets to work. Goggles show where future walls go."]},
            "builder": {"title": "Builder", "text": ["The first and the main one. Builds everything, including his own upgrade. The resource scroll shows from your inventory what he lacks right now."]},
            "citizen": {"title": "Citizen Housing", "text": ["A house is room for citizens. The tavern is the first shelter and bait for newcomers."]},
            "warehouse": {"title": "Warehouse and Courier", "text": ["The warehouse stores, racks are shelves, the courier carries. Without a courier the colony stands still: materials lie, workers wait, you wonder."], "rewards": ["Working colony logistics"]},
            "food": {"title": "Food", "text": ["A hungry citizen doesn't work. The cook makes from what the farmer, shepherd and fisher bring; the kitchen and baker widen the menu to dozens of dishes."]},
            "postbox": {"title": "Postbox", "text": ["Order from the warehouse without chasing the courier."]},
            "hospital": {"title": "Hospital and Graveyard", "text": ["The hospital heals. The graveyard buries — and with a totem of undying, brings back."]},
            "mystical": {"title": "Mystical Site", "text": ["Happiness. Happy citizens work faster and fall sick less."]},
        },
    },
    "mc_production": {
        "title": "Colony Production", "subtitle": "From forest and mine to smithy and glassblower",
        "intro": ["The colony can make nearly anything once the chains are set: lumberjack gives logs, sawmill gives products, miner gives ore, smeltery gives ingots, blacksmith gives tools. Your job is deciding what comes first."],
        "quests": {
            "lumberjack": {"title": "Lumberjack", "text": ["Fells and replants. Knows every wood, BOP included."]},
            "sawmill": {"title": "Sawmill", "text": ["Planks, doors, stairs, furniture — on the builder's orders."]},
            "miner": {"title": "Miner", "text": ["Digs a mine in levels. The stonemason cuts stone, the crusher grinds cobble to gravel and sand, the sifter shakes rarities from the soil."]},
            "smeltery": {"title": "Smelteries", "text": ["Ore to ingots; stone and sand in the stone one. Level is furnace count."]},
            "blacksmith": {"title": "Blacksmith and Mechanic", "text": ["Blacksmith — tools and armor; mechanic — mechanisms, including other mods'. Fletcher, glassblower, dyer cover the rest."]},
            "animals": {"title": "Livestock", "text": ["Shepherd, cowboy, swineherd, chicken herder, rabbits, bees, stable."]},
            "plants": {"title": "Horticulture", "text": ["Plantation — cane, bamboo, cactus. Florist — flowers. Composter — fertilizer."]},
            "fisherman": {"title": "Fisherman", "text": ["Fish and what lies on the bottom."]},
            "nether": {"title": "Nether Worker", "text": ["Goes on expeditions and brings quartz, gold, trophies. Or doesn't."]},
            "quarry": {"title": "Quarry", "text": ["A pit to bedrock and everything that was in it."]},
            "concrete": {"title": "Other Production", "text": ["Concrete, potions, mystical ingredients."]},
        },
    },
    "mc_research": {
        "title": "Science and Growth", "subtitle": "University, school, library and research",
        "intro": [],
        "quests": {
            "library": {"title": "Library", "text": ["Scholars raise everyone else's skills."]},
            "school": {"title": "School", "text": ["Children grow up smarter than their parents."]},
            "university": {"title": "University", "text": ["The research tree: civilization, technology, war, supply. Fifth building levels open only here."], "rewards": ["Access to the research tree"]},
            "tome": {"title": "Ancient Tome", "text": ["Drops from raiders. Needed by research."]},
            "enchanter": {"title": "Enchanter", "text": ["Gathers experience from workers, makes books and scrolls: teleport, buff, guard summon."]},
            "quests": {"title": "Colony Quests", "text": ["Citizens ask. The log remembers. Rewards — experience, rarities, tokens."]},
        },
    },
    "mc_military": {
        "title": "Defense", "subtitle": "Guards, barracks and repelling raids",
        "intro": ["Barbarians, pirates, mummies, norsemen, amazons — who comes depends on the biome. How many and how often — on colony size. A late colony without a garrison doesn't live to morning."],
        "quests": {
            "guardtower": {"title": "Guard Tower", "text": ["Tower — guard. Archer or knight, gear from the warehouse."]},
            "barracks": {"title": "Barracks", "text": ["Up to four towers in one building. A garrison."]},
            "training": {"title": "Training", "text": ["Academy for knights, archery for archers."]},
            "walls": {"title": "Walls and Gates", "text": ["Gates open for your own. The gatehouse holds a wall section."]},
            "banner": {"title": "Rally Banner", "text": ["All guards — to one point. When the wall is breached."]},
            "raid": {"title": "Raid Repelled", "text": ["The chief falls — and so does his sword. Raids are announced in chat beforehand; the night after is long."], "rewards": ["Trophies and confidence in the defense"]},
        },
    },
    "mc_build": {
        "title": "Construction and Styles", "subtitle": "Structurize, Domum Ornamentum and Multi-Piston",
        "intro": [],
        "quests": {
            "scepter": {"title": "Structurize Tools", "text": ["The scepter selects, the shape tool builds spheres and domes, the caliper measures."]},
            "substitution": {"title": "Substitution Blocks", "text": ["Air, solid, fluid, tag — the schematic adapts to the terrain itself."]},
            "cutter": {"title": "Architect's Cutter", "text": ["Brick, tile, timber frame, panels, lights, doors, carpets — from any materials in hundreds of combinations. All colony styles stand on this."], "rewards": ["A huge palette of building materials"]},
            "timberframe": {"title": "Timber Frame", "text": ["Wood and infill. The medieval look is recognized by it."]},
            "multipiston": {"title": "Multi-Piston", "text": ["Dozens of blocks at once over a set distance. Drawbridges, gates, roofs."]},
            "decoration": {"title": "Decoration Controller", "text": ["Decor the builder raises alongside buildings."]},
        },
    },
}
