# -*- coding: utf-8 -*-
"""Английские тексты книги и строки интерфейса на обоих языках.

Переводы глав лежат в модулях en_*.py и собираются здесь в словарь EN:
EN[chapter_id] = {"title", "subtitle", "intro": [...],
                  "quests": {quest_id: {"title", "text": [...], "tasks": [...], "rewards": [...]}}}
"""
import importlib
import os

HERE = os.path.dirname(os.path.abspath(__file__))

EN = {}
for name in sorted(os.listdir(HERE)):
    if name.startswith("en_") and name.endswith(".py"):
        mod = importlib.import_module(name[:-3])
        EN.update(getattr(mod, "EN", {}))

SECTIONS_EN = {
    "start": "Getting Started", "story": "Storylines", "world": "World & Exploration",
    "create": "Create: Mechanics", "createx": "Create: Extensions", "ie": "Immersive Engineering",
    "mek": "Mekanism", "storage": "Storage & Logistics", "colony": "Colony", "dim": "Other Worlds",
    "eternal": "Eternal Tales", "life": "Home & Comfort", "trials": "Trials", "final": "Finale",
    "endgame": "Endgame", "more": "Beyond the Path",
    "magic": "Magic", "tech2": "Industry II", "space": "Space", "hunt": "The Hunt",
}
SECTIONS_RU = {
    "start": "Начало пути", "story": "Сюжетные линии", "world": "Мир и разведка",
    "create": "Create: механика", "createx": "Create: расширения", "ie": "Immersive Engineering",
    "mek": "Mekanism", "storage": "Хранение и логистика", "colony": "Колония", "dim": "Иные миры",
    "eternal": "Eternal Tales", "life": "Быт и уют", "trials": "Испытания", "final": "Финал",
    "endgame": "Эндгейм", "more": "За пределами пути",
    "magic": "Магия", "tech2": "Индустрия II", "space": "Космос", "hunt": "Охота",
}

UI_RU = {
    "key.categories.codex": "Кодекс",
    "key.codex.open": "Открыть Кодекс",
    "codex.title": "Кодекс",
    "codex.ui.search": "Поиск…",
    "codex.ui.not_loaded": "Книга не загружена",
    "codex.ui.mode.server": "сервер",
    "codex.ui.mode.local": "локально",
    "codex.ui.state.done": "Выполнено",
    "codex.ui.state.done_claimed": "Выполнено, награда получена",
    "codex.ui.state.claimable": "Цели выполнены — заберите награду",
    "codex.ui.state.open": "Доступно",
    "codex.ui.state.locked": "Заблокировано",
    "codex.ui.tasks": "Цели",
    "codex.ui.reward": "Награда",
    "codex.ui.xp": "Опыт: %s",
    "codex.ui.claim": "Получить награду",
    "codex.ui.claim_consume": "Сдать предметы и получить награду",
    "codex.ui.local_notice": "Без мода на сервере предметы не выдаются и не забираются.",
    "codex.ui.jei_hint": "ЛКМ по предмету — рецепт, ПКМ — где применяется.",
    "codex.ui.read": "[✔] Прочитано",
    "codex.ui.mark_read": "[ ] Отметить прочитанным",
    "codex.ui.task.consume": "Сдать: %s",
    "codex.ui.task.advancement": "Достижение: %s",
    "codex.ui.task.dimension": "Побывать в измерении: %s",
    "codex.ui.task.biome": "Найти биом: %s",
    "codex.ui.task.check": "Отметить вручную",
    "codex.ui.task.ponder": "Посмотреть сцену Ponder для: %s",
    "codex.ui.tip.claim": "Награда ждёт — откройте задание",
    "codex.ui.tip.locked": "Требует предыдущие задания",
    "codex.ui.tip.lore": "Справочный узел",
    "codex.toast.done": "Кодекс: задание выполнено",
    "codex.msg.prefix": "Кодекс: ",
    "codex.msg.done": "задание выполнено — ",
    "codex.msg.claimed": "награда получена — ",
    "codex.msg.not_enough": "Кодекс: не хватает предметов для сдачи",
}
UI_EN = {
    "key.categories.codex": "Codex",
    "key.codex.open": "Open Codex",
    "codex.title": "Codex",
    "codex.ui.search": "Search…",
    "codex.ui.not_loaded": "Book not loaded",
    "codex.ui.mode.server": "server",
    "codex.ui.mode.local": "local",
    "codex.ui.state.done": "Completed",
    "codex.ui.state.done_claimed": "Completed, reward claimed",
    "codex.ui.state.claimable": "Objectives met — claim your reward",
    "codex.ui.state.open": "Available",
    "codex.ui.state.locked": "Locked",
    "codex.ui.tasks": "Objectives",
    "codex.ui.reward": "Reward",
    "codex.ui.xp": "Experience: %s",
    "codex.ui.claim": "Claim reward",
    "codex.ui.claim_consume": "Turn in items and claim reward",
    "codex.ui.local_notice": "Without the mod on the server, items are neither given nor taken.",
    "codex.ui.jei_hint": "Left-click an item for its recipe, right-click for its uses.",
    "codex.ui.read": "[✔] Read",
    "codex.ui.mark_read": "[ ] Mark as read",
    "codex.ui.task.consume": "Turn in: %s",
    "codex.ui.task.advancement": "Advancement: %s",
    "codex.ui.task.dimension": "Visit dimension: %s",
    "codex.ui.task.biome": "Find biome: %s",
    "codex.ui.task.check": "Mark manually",
    "codex.ui.task.ponder": "Watch the Ponder scene for: %s",
    "codex.ui.tip.claim": "A reward is waiting — open the quest",
    "codex.ui.tip.locked": "Requires previous quests",
    "codex.ui.tip.lore": "Reference node",
    "codex.toast.done": "Codex: quest completed",
    "codex.msg.prefix": "Codex: ",
    "codex.msg.done": "quest completed — ",
    "codex.msg.claimed": "reward claimed — ",
    "codex.msg.not_enough": "Codex: not enough items to turn in",
}

UI_RU.update({
    'codex.ui.maps': 'Карты', 'codex.ui.fit': 'Вписать',
    'codex.ui.overview': 'Обзор', 'codex.ui.next_match': 'Далее',
    'codex.ui.close_detail': 'Скрыть', 'codex.ui.close': 'Закрыть',
    'codex.ui.legend': 'Зелёный: готово · Золото: доступно · Пунктир: любой путь · ◇: необязательно',
    'codex.ui.navigation': 'Перетаскивайте карту мышью. Колесо меняет масштаб под курсором; Home показывает всю карту. ПКМ закрепляет задание. Поиск: Enter или F3 переходит к следующему результату. Ссылки в задании ведут к предпосылкам и следующим шагам.',
    'codex.ui.optional': 'Необязательная ветка',
    'codex.ui.requires_all': 'Нужно выполнить всё:',
    'codex.ui.requires_any': 'Нужно выполнить хотя бы одно:',
    'codex.ui.opens_next': 'Открывает следующие шаги:',
})
UI_EN.update({
    'codex.ui.maps': 'Maps', 'codex.ui.fit': 'Fit',
    'codex.ui.overview': 'Overview', 'codex.ui.next_match': 'Next',
    'codex.ui.close_detail': 'Hide', 'codex.ui.close': 'Close',
    'codex.ui.legend': 'Green: done · Gold: available · Dashed: any path · ◇: optional',
    'codex.ui.navigation': 'Drag to pan. Scroll to zoom at the cursor; Home fits the map. Right-click pins a quest. Search: Enter or F3 jumps to the next match. Quest links lead to prerequisites and next steps.',
    'codex.ui.optional': 'Optional branch',
    'codex.ui.requires_all': 'Complete all:',
    'codex.ui.requires_any': 'Complete at least one:',
    'codex.ui.opens_next': 'Opens next steps:',
})

UI_RU.update({
    'codex.ui.cover': 'Обложка',
    'codex.welcome.title': 'Codex Aethernum',
    'codex.welcome.eyebrow': 'ПУТЕВОДИТЕЛЬ ПО ВАШЕМУ МИРУ',
    'codex.welcome.purpose': 'У каждого большого открытия есть первый шаг. Кодекс поможет пройти путь от первой мастерской до сложных производств, дальних экспедиций и магии — даже если вы впервые знакомитесь с модами.',
    'codex.welcome.promise': 'Выберите интересную ветку. Внутри — подготовка, порядок действий и объяснение результата. Связи между заданиями подскажут, какие знания и инструменты понадобятся дальше.',
    'codex.welcome.progress': '%s открытий в книге · %s уже сделано',
    'codex.welcome.how': 'КАК ЧИТАТЬ КОДЕКС',
    'codex.welcome.step1.title': 'Найдите свой путь',
    'codex.welcome.step1.body': 'Выберите карту и откройте узел. Сплошная связь требует предыдущего шага, пунктир предлагает выбор. Ромб отмечает необязательную ветку. Поиск найдёт название задания или предмет.',
    'codex.welcome.step2.title': 'Превратите знание в дело',
    'codex.welcome.step2.body': 'Прочитайте описание и выполните цели. Предметы и достижения учитываются автоматически. Ручную цель отмечайте после проверки результата. Кнопка сдачи забирает указанные ресурсы и выдаёт награду.',
    'codex.welcome.step3.title': 'Держите карту под рукой',
    'codex.welcome.step3.body': 'Перетаскивайте карту, приближайте колесом, нажмите Home для общего вида. ПКМ закрепляет задание. Клик по предмету открывает JEI; ссылки ведут к соседним шагам. Клавиша книги и Esc закрывают экран.',
    'codex.welcome.open': 'Открыть книгу',
    'codex.welcome.continue': 'Продолжить путь',
    'codex.welcome.beginning': 'К началу пути',
})
UI_EN.update({
    'codex.ui.cover': 'Cover',
    'codex.welcome.title': 'Codex Aethernum',
    'codex.welcome.eyebrow': 'A FIELD GUIDE TO YOUR WORLD',
    'codex.welcome.purpose': 'Every great discovery begins with a first step. The Codex guides you from your first workshop to complex production lines, distant expeditions and magic, even if these mods are entirely new to you.',
    'codex.welcome.promise': 'Choose a branch that interests you. Each quest explains preparation, actions and results. Connections show which knowledge and tools you will need next.',
    'codex.welcome.progress': '%s discoveries in the book · %s completed',
    'codex.welcome.how': 'HOW TO READ THE CODEX',
    'codex.welcome.step1.title': 'Find your path',
    'codex.welcome.step1.body': 'Choose a map and open a node. Solid links require previous steps; dashed links offer alternatives. Diamonds mark optional branches. Search finds quest titles or item identifiers.',
    'codex.welcome.step2.title': 'Put knowledge to work',
    'codex.welcome.step2.body': 'Read the explanation and complete its objectives. Items and advancements are tracked automatically. Tick manual goals after checking the result. Turn-in buttons consume the listed resources and give rewards.',
    'codex.welcome.step3.title': 'Keep your bearings',
    'codex.welcome.step3.body': 'Drag the map, zoom with the wheel and press Home for an overview. Right-click pins a quest. Click an item for JEI recipes; follow links to related steps. The book key and Esc close the screen.',
    'codex.welcome.open': 'Open the book',
    'codex.welcome.continue': 'Continue your journey',
    'codex.welcome.beginning': 'The first steps',
})

UI_RU.update({
    'codex.ui.settings': 'Настройки', 'codex.ui.back': 'Назад', 'codex.ui.on': 'Вкл', 'codex.ui.off': 'Выкл',
    'codex.ui.related_steps': 'Связанные предыдущие шаги:',
    'codex.settings.title': 'НАСТРОЙКИ КОДЕКСА',
    'codex.settings.intro': 'Порядок прохождения хранится в вашем прогрессе на сервере и действует только для вас. Остальные настройки относятся к этому клиенту.',
    'codex.settings.order': 'Порядок прохождения',
    'codex.settings.order.strict': 'Строгий',
    'codex.settings.order.strict.desc': 'Задание открывается после всех предпосылок, включая задания других карт. Так устроена прогрессия в GTNH.',
    'codex.settings.order.map': 'Внутри карты',
    'codex.settings.order.map.desc': 'Нужны только предыдущие шаги той же карты. Связи с другими картами остаются подсказками и не блокируют задание.',
    'codex.settings.order.free': 'Свободный',
    'codex.settings.order.free.desc': 'Все задания доступны сразу, уже сделанное засчитывается. Связи между заданиями служат только для навигации.',
    'codex.settings.tooltips': 'Подсказки о предметах',
    'codex.settings.tooltips.desc': 'При наведении на предмет цели или награды показывать его название, мод и описание.',
    'codex.settings.toasts': 'Уведомления о выполнении',
    'codex.settings.toasts.desc': 'Всплывающее сообщение в углу экрана, когда задание выполнено.',
    'codex.settings.cover': 'При открытии книги',
    'codex.settings.cover.desc': 'Показывать обложку с кратким руководством или сразу переходить к карте.',
    'codex.settings.cover.on': 'Обложка', 'codex.settings.cover.off': 'Сразу карта',
})
UI_EN.update({
    'codex.ui.settings': 'Settings', 'codex.ui.back': 'Back', 'codex.ui.on': 'On', 'codex.ui.off': 'Off',
    'codex.ui.related_steps': 'Related earlier steps:',
    'codex.settings.title': 'CODEX SETTINGS',
    'codex.settings.intro': 'The progression order is stored in your server-side progress and applies only to you. The other settings belong to this client.',
    'codex.settings.order': 'Progression order',
    'codex.settings.order.strict': 'Strict',
    'codex.settings.order.strict.desc': 'A quest unlocks after all its prerequisites, including quests on other maps. This is how GTNH progression works.',
    'codex.settings.order.map': 'Within the map',
    'codex.settings.order.map.desc': 'Only earlier steps of the same map are required. Links to other maps remain hints and never block a quest.',
    'codex.settings.order.free': 'Free',
    'codex.settings.order.free.desc': 'Every quest is available at once and finished work counts immediately. Links between quests are navigation only.',
    'codex.settings.tooltips': 'Item tooltips',
    'codex.settings.tooltips.desc': 'Hovering an objective or reward item shows its name, mod and description.',
    'codex.settings.toasts': 'Completion notifications',
    'codex.settings.toasts.desc': 'A pop-up in the corner of the screen when a quest is completed.',
    'codex.settings.cover': 'When opening the book',
    'codex.settings.cover.desc': 'Show the cover with the short guide, or go straight to the map.',
    'codex.settings.cover.on': 'Cover', 'codex.settings.cover.off': 'Map first',
})
UI_RU.update({
    'codex.hint.obtain': 'Как получить:',
    'codex.hint.none': 'В рецептах и таблицах добычи сборки не найдено — проверьте JEI',
    'codex.hint.drop': 'Выпадает с: %s',
    'codex.hint.chest': 'В сундуках: %s',
    'codex.hint.block': 'Добывается из: %s',
    'codex.hint.world': 'Встречается в биомах: %s',
    'codex.hint.habitat': '%s (обитает: %s)',
    'codex.hint.tag': '%s и подобные',
    'codex.hint.advancement': 'Достижение мода:',
    'codex.hint.biome': 'Посетить биом: %s',
    'codex.hint.dimension': 'Посетить измерение: %s',
    'codex.hint.check': 'Ручная цель — отметьте после проверки:',
    'codex.hint.ponder': 'Посмотреть сцену Ponder этого предмета',
    'codex.recipe.minecraft.crafting_shaped': 'Верстак',
    'codex.recipe.crafting_shaped': 'Верстак',
    'codex.recipe.minecraft.crafting_shapeless': 'Верстак',
    'codex.recipe.crafting_shapeless': 'Верстак',
    'codex.recipe.minecraft.smelting': 'Печь',
    'codex.recipe.smelting': 'Печь',
    'codex.recipe.minecraft.blasting': 'Плавильная печь',
    'codex.recipe.minecraft.smoking': 'Коптильня',
    'codex.recipe.minecraft.campfire_cooking': 'Костёр',
    'codex.recipe.minecraft.stonecutting': 'Камнерез',
    'codex.recipe.minecraft.smithing_transform': 'Кузнечный стол',
    'codex.recipe.create.mechanical_crafting': 'Механический верстак Create',
    'codex.recipe.create.sequenced_assembly': 'Последовательная сборка Create',
    'codex.recipe.create.crushing': 'Дробильные колёса Create',
    'codex.recipe.create.milling': 'Жернова Create',
    'codex.recipe.create.pressing': 'Механический пресс Create',
    'codex.recipe.create.mixing': 'Смеситель Create',
    'codex.recipe.create.compacting': 'Пресс над чашей Create',
    'codex.recipe.create.cutting': 'Механическая пила Create',
    'codex.recipe.create.deploying': 'Установщик Create',
    'codex.recipe.create.filling': 'Разливочная машина Create',
    'codex.recipe.create.splashing': 'Промывка вентилятором Create',
    'codex.recipe.create.haunting': 'Одержимость вентилятором Create',
    'codex.recipe.create.item_application': 'Применить предмет к блоку (Create)',
    'codex.recipe.mekanism.metallurgic_infusing': 'Металлургический инфузор Mekanism',
    'codex.recipe.mekanism.enriching': 'Обогатительная камера Mekanism',
    'codex.recipe.mekanism.crushing': 'Дробилка Mekanism',
    'codex.recipe.mekanism.combining': 'Комбинатор Mekanism',
    'codex.recipe.mekanism.injecting': 'Химическая инжекционная камера Mekanism',
    'codex.recipe.mekanism.purifying': 'Очистительная камера Mekanism',
    'codex.recipe.mekanism.reaction': 'Камера реакции под давлением Mekanism',
    'codex.recipe.mekanism.crystallizing': 'Химический кристаллизатор Mekanism',
    'codex.recipe.mekanism.nucleosynthesizing': 'Антипротонный нуклеосинтезатор Mekanism',
    'codex.recipe.mekanism.sawing': 'Прецизионная лесопилка Mekanism',
    'codex.recipe.mekanism.mek_data': 'Верстак (с сохранением данных)',
    'codex.recipe.mekanism.compressing': 'Осмиевый компрессор Mekanism',
    'codex.recipe.mekanism.smelting': 'Энергетическая печь Mekanism',
    'codex.recipe.immersiveengineering.crusher': 'Дробилка IE',
    'codex.recipe.immersiveengineering.metal_press': 'Металлопресс IE',
    'codex.recipe.immersiveengineering.arc_furnace': 'Дуговая печь IE',
    'codex.recipe.immersiveengineering.blueprint': 'Верстак инженера по чертежу IE',
    'codex.recipe.immersiveengineering.sawmill': 'Лесопилка IE',
    'codex.recipe.immersiveengineering.cloche': 'Садовая камера IE',
    'codex.recipe.immersiveengineering.bottling_machine': 'Разливочная машина IE',
    'codex.recipe.immersiveengineering.alloy': 'Сплавная печь IE',
    'codex.recipe.immersiveengineering.blast_furnace': 'Домна IE',
    'codex.recipe.immersiveengineering.coke_oven': 'Коксовая печь IE',
    'codex.recipe.immersiveengineering.squeezer': 'Пресс-выжималка IE',
    'codex.recipe.immersiveengineering.fermenter': 'Ферментер IE',
    'codex.recipe.immersiveengineering.refinery': 'Нефтеперегонный завод IE',
    'codex.recipe.immersiveengineering.mixer': 'Смеситель IE',
    'codex.recipe.immersiveengineering.turn_and_copy': 'Верстак (копия)',
    'codex.recipe.immersiveengineering.revolver_assembly': 'Сборка револьвера IE',
    'codex.recipe.immersiveengineering.shaped_fluid': 'Верстак с жидкостью IE',
    'codex.recipe.botania.mana_infusion': 'Манапул Botania',
    'codex.recipe.botania.elven_trade': 'Эльфийский портал Botania',
    'codex.recipe.botania.runic_altar': 'Рунический алтарь Botania',
    'codex.recipe.botania.petal_apothecary': 'Аптекарский горшок Botania',
    'codex.recipe.botania.pure_daisy': 'Чистая маргаритка Botania',
    'codex.recipe.botania.terra_plate': 'Терра-пластина Botania',
    'codex.recipe.botania.brew': 'Варочный аппарат Botania',
    'codex.recipe.ars_nouveau.enchanting_apparatus': 'Чарующий аппарат Ars Nouveau',
    'codex.recipe.ars_nouveau.imbuement': 'Камера пропитки Ars Nouveau',
    'codex.recipe.ars_nouveau.glyph': 'Стол писца Ars Nouveau',
    'codex.recipe.ars_nouveau.dye': 'Верстак (окраска)',
    'codex.recipe.ars_nouveau.book_upgrade': 'Улучшение книги Ars Nouveau',
    'codex.recipe.mysticalagriculture.infusion': 'Алтарь пропитки MA',
    'codex.recipe.mysticalagriculture.reprocessor': 'Переработчик семян MA',
    'codex.recipe.farmersdelight.cooking': 'Котелок Farmer’s Delight',
    'codex.recipe.farmersdelight.cutting': 'Разделочная доска',
    'codex.recipe.ad_astra.compressing': 'Компрессор Ad Astra',
    'codex.recipe.ad_astra.nasa_workbench': 'Верстак NASA',
    'codex.recipe.ad_astra.alloying': 'Сплавная печь Ad Astra',
    'codex.recipe.apothic_enchanting.infusion': 'Инфузия зачарованием (Apotheosis)',
    'codex.recipe.apothic_enchanting.keep_nbt_infusion': 'Инфузия зачарованием (Apotheosis)',
    'codex.recipe.apotheosis.salvaging': 'Стол разборки Apotheosis',
    'codex.recipe.apotheosis.sized_upgrade_recipe': 'Верстак (улучшение)',
    'codex.recipe.eternal_tales.interdimensional_creator_type': 'Межпространственный создатель ET',
    'codex.recipe.eternal_tales.trading_recipe': 'Обмен у торговца ET',
    'codex.recipe.eternal_tales.jei_drop_inverted': 'Выпадает при использовании',
    'codex.recipe.eternal_tales.jei_drop_recipe': 'Выпадает при использовании',
    'codex.recipe.eternal_tales.jei_right_click': 'ПКМ по блоку',
    'codex.recipe.eternal_tales.shed_recipe': 'Сбрасывает существо',
    'codex.recipe.createaddition.rolling': 'Прокатный стан Create Addition',
    'codex.recipe.createaddition.charging': 'Зарядка (Create Addition)',
    'codex.recipe.create_new_age.energising': 'Энергизация (Create: New Age)',
    'codex.recipe.powah.energizing': 'Энергизирующая установка Powah',
    'codex.recipe.industrialforegoing.dissolution_chamber': 'Камера растворения IF',
    'codex.recipe.industrialforegoing.laser_drill_ore': 'Лазерный бур IF',
    'codex.recipe.industrialforegoing.stonework_generate': 'Каменная фабрика IF',
    'codex.recipe.pneumaticcraft.crafting_shaped_pressurizable': 'Верстак',
    'codex.recipe.pneumaticcraft.pressure_chamber': 'Барокамера PneumaticCraft',
    'codex.recipe.pneumaticcraft.thermo_plant': 'Термопрессовая установка',
    'codex.recipe.pneumaticcraft.assembly': 'Сборочная система PneumaticCraft',
    'codex.recipe.refurbished_furniture.workbench_constructing': 'Верстак Refurbished Furniture',
    'codex.recipe.aether.enchanting': 'Алтарь Aether',
    'codex.recipe.aether.freezing': 'Морозилка Aether',
    'codex.recipe.cataclysm.weapon_fusion': 'Наковальня механического слияния Cataclysm',
    'codex.recipe.irons_spellbooks.alchemist_cauldron_fill': 'Котёл алхимика Iron’s Spells',
    'codex.recipe.sophisticatedcore.upgrade_next_tier': 'Верстак (следующий уровень)',
    'codex.recipe.sophisticatedbackpacks.backpack_upgrade': 'Верстак (улучшение рюкзака)',
    'codex.recipe.cucumber.shaped_no_mirror': 'Верстак',
    'codex.recipe.botania.crafting_shaped_mana_upgrade': 'Верстак',
    'codex.recipe.botania.crafting_shaped_armor_upgrade': 'Верстак',
    'codex.recipe.botania.crafting_shaped_wand': 'Верстак',
    'codex.recipe.mekanismtools.paxel': 'Верстак',
})
UI_EN.update({
    'codex.hint.obtain': 'How to obtain:',
    'codex.hint.none': 'Not found in this pack’s recipes or loot tables — check JEI',
    'codex.hint.drop': 'Dropped by: %s',
    'codex.hint.chest': 'In chests: %s',
    'codex.hint.block': 'Mined from: %s',
    'codex.hint.world': 'Found in biomes: %s',
    'codex.hint.habitat': '%s (lives in: %s)',
    'codex.hint.tag': '%s and similar',
    'codex.hint.advancement': 'Mod advancement:',
    'codex.hint.biome': 'Visit biome: %s',
    'codex.hint.dimension': 'Visit dimension: %s',
    'codex.hint.check': 'Manual goal — tick after checking:',
    'codex.hint.ponder': 'Watch this item’s Ponder scene',
    'codex.recipe.minecraft.crafting_shaped': 'Crafting table',
    'codex.recipe.crafting_shaped': 'Crafting table',
    'codex.recipe.minecraft.crafting_shapeless': 'Crafting table',
    'codex.recipe.crafting_shapeless': 'Crafting table',
    'codex.recipe.minecraft.smelting': 'Furnace',
    'codex.recipe.smelting': 'Furnace',
    'codex.recipe.minecraft.blasting': 'Blast furnace',
    'codex.recipe.minecraft.smoking': 'Smoker',
    'codex.recipe.minecraft.campfire_cooking': 'Campfire',
    'codex.recipe.minecraft.stonecutting': 'Stonecutter',
    'codex.recipe.minecraft.smithing_transform': 'Smithing table',
    'codex.recipe.create.mechanical_crafting': 'Create mechanical crafter',
    'codex.recipe.create.sequenced_assembly': 'Create sequenced assembly',
    'codex.recipe.create.crushing': 'Create crushing wheels',
    'codex.recipe.create.milling': 'Create millstone',
    'codex.recipe.create.pressing': 'Create mechanical press',
    'codex.recipe.create.mixing': 'Create mixer',
    'codex.recipe.create.compacting': 'Create press over basin',
    'codex.recipe.create.cutting': 'Create mechanical saw',
    'codex.recipe.create.deploying': 'Create deployer',
    'codex.recipe.create.filling': 'Create spout',
    'codex.recipe.create.splashing': 'Create fan washing',
    'codex.recipe.create.haunting': 'Create fan haunting',
    'codex.recipe.create.item_application': 'Apply item to block (Create)',
    'codex.recipe.mekanism.metallurgic_infusing': 'Mekanism metallurgic infuser',
    'codex.recipe.mekanism.enriching': 'Mekanism enrichment chamber',
    'codex.recipe.mekanism.crushing': 'Mekanism crusher',
    'codex.recipe.mekanism.combining': 'Mekanism combiner',
    'codex.recipe.mekanism.injecting': 'Mekanism chemical injection chamber',
    'codex.recipe.mekanism.purifying': 'Mekanism purification chamber',
    'codex.recipe.mekanism.reaction': 'Mekanism pressurized reaction chamber',
    'codex.recipe.mekanism.crystallizing': 'Mekanism chemical crystallizer',
    'codex.recipe.mekanism.nucleosynthesizing': 'Mekanism antiprotonic nucleosynthesizer',
    'codex.recipe.mekanism.sawing': 'Mekanism precision sawmill',
    'codex.recipe.mekanism.mek_data': 'Crafting table (keeps data)',
    'codex.recipe.mekanism.compressing': 'Mekanism osmium compressor',
    'codex.recipe.mekanism.smelting': 'Mekanism energized smelter',
    'codex.recipe.immersiveengineering.crusher': 'IE crusher',
    'codex.recipe.immersiveengineering.metal_press': 'IE metal press',
    'codex.recipe.immersiveengineering.arc_furnace': 'IE arc furnace',
    'codex.recipe.immersiveengineering.blueprint': 'IE engineer’s workbench (blueprint)',
    'codex.recipe.immersiveengineering.sawmill': 'IE sawmill',
    'codex.recipe.immersiveengineering.cloche': 'IE garden cloche',
    'codex.recipe.immersiveengineering.bottling_machine': 'IE bottling machine',
    'codex.recipe.immersiveengineering.alloy': 'IE alloy kiln',
    'codex.recipe.immersiveengineering.blast_furnace': 'IE blast furnace',
    'codex.recipe.immersiveengineering.coke_oven': 'IE coke oven',
    'codex.recipe.immersiveengineering.squeezer': 'IE squeezer',
    'codex.recipe.immersiveengineering.fermenter': 'IE fermenter',
    'codex.recipe.immersiveengineering.refinery': 'IE refinery',
    'codex.recipe.immersiveengineering.mixer': 'IE mixer',
    'codex.recipe.immersiveengineering.turn_and_copy': 'Crafting table (copy)',
    'codex.recipe.immersiveengineering.revolver_assembly': 'IE revolver assembly',
    'codex.recipe.immersiveengineering.shaped_fluid': 'IE crafting with fluid',
    'codex.recipe.botania.mana_infusion': 'Botania mana pool',
    'codex.recipe.botania.elven_trade': 'Botania elven portal',
    'codex.recipe.botania.runic_altar': 'Botania runic altar',
    'codex.recipe.botania.petal_apothecary': 'Botania petal apothecary',
    'codex.recipe.botania.pure_daisy': 'Botania pure daisy',
    'codex.recipe.botania.terra_plate': 'Botania terra plate',
    'codex.recipe.botania.brew': 'Botania brewery',
    'codex.recipe.ars_nouveau.enchanting_apparatus': 'Ars Nouveau enchanting apparatus',
    'codex.recipe.ars_nouveau.imbuement': 'Ars Nouveau imbuement chamber',
    'codex.recipe.ars_nouveau.glyph': 'Ars Nouveau scribe’s table',
    'codex.recipe.ars_nouveau.dye': 'Crafting table (dye)',
    'codex.recipe.ars_nouveau.book_upgrade': 'Ars Nouveau book upgrade',
    'codex.recipe.mysticalagriculture.infusion': 'MA infusion altar',
    'codex.recipe.mysticalagriculture.reprocessor': 'MA seed reprocessor',
    'codex.recipe.farmersdelight.cooking': 'Farmer’s Delight cooking pot',
    'codex.recipe.farmersdelight.cutting': 'Cutting board',
    'codex.recipe.ad_astra.compressing': 'Ad Astra compressor',
    'codex.recipe.ad_astra.nasa_workbench': 'NASA workbench',
    'codex.recipe.ad_astra.alloying': 'Ad Astra alloy furnace',
    'codex.recipe.apothic_enchanting.infusion': 'Enchantment infusion (Apotheosis)',
    'codex.recipe.apothic_enchanting.keep_nbt_infusion': 'Enchantment infusion (Apotheosis)',
    'codex.recipe.apotheosis.salvaging': 'Apotheosis salvaging table',
    'codex.recipe.apotheosis.sized_upgrade_recipe': 'Crafting table (upgrade)',
    'codex.recipe.eternal_tales.interdimensional_creator_type': 'ET interdimensional creator',
    'codex.recipe.eternal_tales.trading_recipe': 'ET trader exchange',
    'codex.recipe.eternal_tales.jei_drop_inverted': 'Dropped when used',
    'codex.recipe.eternal_tales.jei_drop_recipe': 'Dropped when used',
    'codex.recipe.eternal_tales.jei_right_click': 'Right-click a block',
    'codex.recipe.eternal_tales.shed_recipe': 'Shed by a creature',
    'codex.recipe.createaddition.rolling': 'Create Addition rolling mill',
    'codex.recipe.createaddition.charging': 'Charging (Create Addition)',
    'codex.recipe.create_new_age.energising': 'Energising (Create: New Age)',
    'codex.recipe.powah.energizing': 'Powah energizing orb',
    'codex.recipe.industrialforegoing.dissolution_chamber': 'IF dissolution chamber',
    'codex.recipe.industrialforegoing.laser_drill_ore': 'IF laser drill',
    'codex.recipe.industrialforegoing.stonework_generate': 'IF stonework factory',
    'codex.recipe.pneumaticcraft.crafting_shaped_pressurizable': 'Crafting table',
    'codex.recipe.pneumaticcraft.pressure_chamber': 'PneumaticCraft pressure chamber',
    'codex.recipe.pneumaticcraft.thermo_plant': 'Thermopneumatic processing plant',
    'codex.recipe.pneumaticcraft.assembly': 'PneumaticCraft assembly system',
    'codex.recipe.refurbished_furniture.workbench_constructing': 'Refurbished Furniture workbench',
    'codex.recipe.aether.enchanting': 'Aether altar',
    'codex.recipe.aether.freezing': 'Aether freezer',
    'codex.recipe.cataclysm.weapon_fusion': 'Cataclysm mechanical fusion anvil',
    'codex.recipe.irons_spellbooks.alchemist_cauldron_fill': 'Iron’s Spells alchemist cauldron',
    'codex.recipe.sophisticatedcore.upgrade_next_tier': 'Crafting table (next tier)',
    'codex.recipe.sophisticatedbackpacks.backpack_upgrade': 'Crafting table (backpack upgrade)',
    'codex.recipe.cucumber.shaped_no_mirror': 'Crafting table',
    'codex.recipe.botania.crafting_shaped_mana_upgrade': 'Crafting table',
    'codex.recipe.botania.crafting_shaped_armor_upgrade': 'Crafting table',
    'codex.recipe.botania.crafting_shaped_wand': 'Crafting table',
    'codex.recipe.mekanismtools.paxel': 'Crafting table',
})

UI_RU['codex.ui.inventory_rules'] = 'Обычные предметные цели запоминают наибольший запас каждого предмета, замеченный в инвентаре. Разные предметы можно показать по очереди; уже учтённую машину снимать не нужно. Для количества больше одного соберите нужный запас одного предмета вместе. Цели «Сдать» требуют все указанные ресурсы при сдаче и забирают их.'
UI_EN['codex.ui.inventory_rules'] = 'Ordinary item goals remember the largest inventory quantity seen for each item. Different items can be shown separately; recorded machinery need not be dismantled. For counts above one, gather the required quantity of that item together. Turn-in goals require all listed supplies at claim time and consume them.'
