# -*- coding: utf-8 -*-
"""Предметные награды для ключевых заданий. Ключ — глобальный идентификатор задания."""
from dsl import loot

REWARDS = {
    "start_first_day/wood": loot(("minecraft:bread", 8), xp=10),
    "start_first_day/backpack": loot(("sophisticatedbackpacks:pickup_upgrade", 1), xp=20),
    "start_first_day/iron": loot(("minecraft:iron_ingot", 16), xp=20),
    "start_first_day/waystone": loot(("waystones:return_scroll", 2), xp=20),
    "start_first_day/base": loot(("minecraft:torch", 64), ("minecraft:oak_planks", 64), xp=30),

    "create_basics/andesite": loot(("create:andesite_alloy", 16), xp=25),
    "create_basics/waterwheel": loot(("create:shaft", 16), ("create:cogwheel", 8), xp=30),
    "create_basics/wrench": loot(("create:goggles", 1), xp=20),
    "create_andesite/press": loot(("create:iron_sheet", 16), xp=30),
    "create_andesite/mixer": loot(("create:basin", 1), ("create:blaze_cake", 2), xp=40),
    "create_andesite/crafter_basic": loot(("create:mechanical_crafter", 4), xp=40),
    "create_fluids/hose": loot(("create:fluid_tank", 8), xp=40),
    "create_copper/boiler": loot(("create:steam_engine", 2), xp=60),
    "create_brass/brass": loot(("create:brass_ingot", 16), xp=40),
    "create_brass/crushing": loot(("create:crushed_raw_iron", 32), xp=50),
    "create_brass/precision": loot(("create:precision_mechanism", 4), xp=80),
    "create_contraptions/tools_contraption": loot(("create:mechanical_drill", 2), xp=50),
    "create_packages/ticker": loot(("create:cardboard", 32), xp=60),
    "create_packages/factory_gauge": loot(("create:factory_gauge", 4), xp=100),
    "create_trains/train": loot(("create:track", 64), xp=100),
    "create_trains/schedule": loot(("create:schedule", 2), xp=40),
    "create_tools/cannon": loot(("minecraft:gunpowder", 32), xp=60),

    "ca_electric/alternator": loot(("createaddition:connector", 8), ("createaddition:copper_spool", 4), xp=50),
    "ca_electric/accumulator": loot(("createaddition:capacitor", 4), xp=40),
    "aero_basics/airship": loot(("aeronautics:white_envelope", 32), xp=120),
    "aero_basics/navigation": loot(("simulated:gyroscopic_mechanism", 2), xp=120),
    "cbc_foundry/shot": loot(("createbigcannons:powder_charge", 16), xp=80),
    "cbc_advanced/autocannon": loot(("createbigcannons:autocannon_cartridge", 32), xp=120),
    "radar/controllers": loot(("create_radar:data_link", 4), xp=100),
    "missiles/mount_missile": loot(("cbcaeronauticsmissiles:rocket_motor", 4), xp=120),

    "ie_start/coke_oven": loot(("immersiveengineering:coal_coke", 32), xp=40),
    "ie_start/blast": loot(("immersiveengineering:ingot_steel", 16), xp=60),
    "ie_start/workbench": loot(("immersiveengineering:blueprint", 1), xp=30),
    "ie_power/dynamo": loot(("immersiveengineering:wirecoil_copper", 4), ("immersiveengineering:connector_lv", 4), xp=40),
    "ie_power/wire_hv": loot(("immersiveengineering:capacitor_mv", 1), xp=60),
    "ie_machines/crusher_ie": loot(("immersiveengineering:steel_scaffolding_standard", 32), xp=60),
    "ie_machines/excavator": loot(("immersiveengineering:coresample", 1), xp=150),
    "ie_chemistry/diesel": loot(("immersiveengineering:biodiesel_bucket", 4), xp=100),
    "ie_gear/drill_ie": loot(("immersiveengineering:drillhead_steel", 1), xp=50),

    "mek_start/steel": loot(("mekanism:ingot_steel", 16), xp=40),
    "mek_start/casing": loot(("mekanism:basic_control_circuit", 8), xp=50),
    "mek_ore/enrichment": loot(("mekanism:upgrade_speed", 2), ("mekanism:upgrade_energy", 2), xp=50),
    "mek_ore/dissolution": loot(("mekanism:alloy_reinforced", 8), xp=150),
    "mek_ore/miner": loot(("mekanism:upgrade_speed", 4), xp=100),
    "mek_power/turbine": loot(("mekanismgenerators:turbine_blade", 16), xp=150),
    "mek_nuclear/reactor": loot(("mekanism:hazmat_mask", 1), ("mekanism:hazmat_gown", 1),
                                ("mekanism:hazmat_pants", 1), ("mekanism:hazmat_boots", 1), xp=200),
    "mek_nuclear/fusion": loot(("mekanism:alloy_atomic", 8), xp=300),
    "mek_gear/mekasuit": loot(("mekanism:module_energy_unit", 2), xp=200),

    "rs_network/controller": loot(("refinedstorage:1k_storage_disk", 2), ("refinedstorage:cable", 16), xp=40),
    "rs_network/grid": loot(("refinedstorage:4k_storage_disk", 1), xp=50),
    "rs_autocraft/autocrafter": loot(("refinedstorage:pattern", 16), xp=60),
    "rs_autocraft/big_project": loot(("refinedstorage:16k_storage_disk", 1), xp=120),

    "mc_found/townhall": loot(("minecraft:bread", 32), ("minecraft:oak_log", 64), xp=50),
    "mc_found/warehouse": loot(("minecolonies:blockminecoloniesrack", 8), xp=60),
    "mc_research/university": loot(("minecraft:book", 16), xp=80),
    "mc_military/raid": loot(("minecraft:iron_ingot", 32), xp=100),

    "dim_aether/gold_dungeon": loot(("aether:golden_amber", 8), xp=250),
    "dim_twilight/cinders": loot(("twilightforest:fiery_ingot", 8), xp=300),
    "dim_twilight/naga": loot(("twilightforest:naga_scale", 8), xp=80),
    "dim_twilight/hydra": loot(("twilightforest:fiery_blood", 4), xp=150),

    "et_overworld/interdim": loot(("eternal_tales:return_ticket", 2), xp=80),
    "et_comets/tree": loot(("eternal_tales:skylite_ingot", 8), xp=120),
    "et_purgatorium/nyetet": loot(("eternal_tales:sun_stone_nugget", 4), xp=180),
    "et_eden/jaghax": loot(("eternal_tales:aragotium_ingot", 4), xp=220),
    "et_rayana/pterion": loot(("eternal_tales:destroyer_eye", 2), xp=220),
    "et_karvat/gods": loot(("eternal_tales:crystal_of_greatness", 1), xp=300),
    "et_volcanech/arahulum": loot(("eternal_tales:truadamantite_ingot", 4), xp=300),
    "et_amber/xaxxas": loot(("eternal_tales:damaged_astral", 1), xp=400),
    "et_unahzaal/unahzaal": loot(("eternal_tales:the_ultimate_bricks", 16), xp=1000),

    "fd_kitchen/feast": loot(("farmersdelight:honey_glazed_ham", 2), xp=40),
    "final_goals/goal_all": loot(("minecraft:nether_star", 1), ("minecraft:enchanted_golden_apple", 4), xp=5000),
}
